# Extracting table header as list

In [1]:
import collections
collections.Callable = collections.abc.Callable

In [2]:
from bs4 import BeautifulSoup, NavigableString
from html_table_extractor.extractor import Extractor
import pandas as pd
import os
import re

In [3]:
relative_path_html = "../HTML/Output_html_Chapter10/kaggle/working/out/output/"
relative_path_pdf = "../HTML/Output_html_Chapter10/kaggle/working/out/pages/"
relative_dictionary_path = "../Dictionary/Chapter10_Attributes.csv"
relative_result_path = "../HTML/Output_html_Chapter10/Chapter10_Attributes.csv"
# Get the absolute path by joining the current directory with the relative path
absolute_path_html = os.path.join(os.getcwd(), relative_path_html)
absolute_path_pdf = os.path.join(os.getcwd(), relative_path_pdf)
absolute_dictionary_path = os.path.join(os.getcwd(), relative_dictionary_path)
absolute_result_path = os.path.join(os.getcwd(), relative_result_path)

In [4]:
absolute_path_html

'/home/riya/Downloads/ADT/2015-16/Processing_Files/../HTML/Output_html_Chapter10/kaggle/working/out/output/'

In [5]:
os.listdir(absolute_path_html)

['output_page_18.html',
 'output_page_15.html',
 'output_page_10.html',
 'output_page_16.html',
 'output_page_1.html',
 'output_page_2.html',
 'output_page_5.html',
 'output_page_11.html',
 'output_page_8.html',
 'output_page_3.html',
 'output_page_13.html',
 'output_page_4.html',
 'output_page_14.html',
 'output_page_9.html',
 'output_page_12.html',
 'output_page_17.html',
 'output_page_7.html',
 'output_page_6.html']

In [6]:
output_list = []

In [7]:
output_list

[]

In [8]:
allowed_two_letter_words = {'sl','sc', 'st', 'cc', 'tp', 'tb', 'ts', 'tg', 'km', 'gm', 'an', 'at', 'by', 'do', 'go', 'if', 'in', 'is', 'it', 'me', 'my', 'no', 'of', 'on', 'or', 'so', 'to', 'up', 'us'}

def replace_td_content(tag):
    if isinstance(tag, NavigableString):
        return  # Skip strings, as they don't have 'contents'

    if tag.name == 'td':
        # Extract only meaningful English words and numbers
        valid_characters = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-.%")
        filtered_content = ''.join(char if char in valid_characters else ' ' for char in tag.get_text())
        
        # Remove extra spaces and words with less than 3 characters
        cleaned_content = ' '.join(word for word in filtered_content.split() if len(word) >= 3 or word.isdigit() or word.lower() in allowed_two_letter_words or word=='%')
        
        # Set the cleaned content as the tag's string
        tag.string = cleaned_content
    elif tag.contents:
        for child in tag.contents:
            replace_td_content(child)

In [9]:
def process_table_cells(target_table):
    if not target_table:
        print("Table not found in the HTML content.")
        return

    flag1 = 0
    flag2 = 0

    # Loop through each row in the table
    for row in target_table.find_all('tr'):
        # Loop through each cell in the row
        if(flag1 == 1 and flag2 == 1):
            row.decompose()
        else : 
            for cell in row.find_all(['td', 'th']):
                # Process the cell content (you can modify this part based on your requirements)
                cell_content = cell.get_text(strip=True)
                if(cell_content == '1'):
                    flag1 = 1
                if(cell_content == '2'):
                    flag2 = 1

In [10]:
# iterate through all file 
for file in os.listdir(absolute_path_html): 
    # Check whether file is in text format or not 
    if file.endswith(".html"): 
        file_path = os.path.join(absolute_path_html, file)
        with open(file_path) as fp:
            soup = BeautifulSoup(fp, "html.parser")
            
            for tag in soup.find_all(attrs={'style': True}):
                tag.attrs.pop('style')
            
            table_tag = soup.find('table')
            
            if table_tag is not None:
                replace_td_content(table_tag)

                process_table_cells(table_tag)

                extractor1 = Extractor(table_tag)
                extractor1.parse()
                output_list.append(extractor1.return_list())
            else:
                print(file_path)

In [11]:
output_list

[[['10.15 EAf jAU No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 EAf jAU No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 EAf jAU No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 EAf jAU No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 EAf jAU No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 EAf jAU No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 EAf jAU No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 EAf jAU No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 EAf jAU No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 EAf jAU No.of Engineering Colleges and Students Year- 2015-16'],
  ['',
   '.ffl',
   'Engineering- Government',
   'Engineering- Government',
   'Engineering- Government',
   'Engineering- Government',
   'Engineering- Private Aided',
   'Engineering- Private Aided',
   'Engineering- Private Aided',
   'Engineering- Private Aided'],
  ['',
   '.ffl',
   'No.of Colleges',
   'Istyear',
   'Istyear',
   'Istyear',
   'No.of Colleges',
   'Istyear',
   'Istyear',
   'Istyear'],
  ['', '.ffl', 'No.of Colleges', '', '', '', 'No.of Colleges', '', '', ''],
  ['',
   '.ffl',
   'No.of Colleges',
   'Male',
   'Female',
   'Total',
   'No.of Colleges',
   'Male',
   'Female',
   'Total'],
  ['1', '2', '640', '641', '642', '643', '644', '645', '646', '647']],
 [['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.'],
  ['Sl.No',
   'Districts',
   'jIndian System of Medicine Colleges Government Istyeartofinalyear',
   'jIndian System of Medicine Colleges Government Istyeartofinalyear',
   'jIndian System of Medicine Colleges Government Istyeartofinalyear',
   'jIndian System of Medicine Colleges Government Istyeartofinalyear',
   '',
   '',
   '',
   ''],
  ['Sl.No',
   'Districts',
   'jIndian System of Medicine Colleges Government Istyeartofinalyear',
   'jIndian System of Medicine Colleges Government Istyeartofinalyear',
   'jIndian System of Medicine Colleges Government Istyeartofinalyear',
   'jIndian System of Medicine Colleges Government Istyeartofinalyear',
   'Indian System of Medicine Colleges Private CAw Istyeartofinalyear aided unaided',
   'Indian System of Medicine Colleges Private CAw Istyeartofinalyear aided unaided',
   'Indian System of Medicine Colleges Private CAw Istyeartofinalyear aided unaided',
   'Indian System of Medicine Colleges Private CAw Istyeartofinalyear aided unaided'],
  ['Sl.No',
   'Districts',
   'Colleges',
   'St udents',
   'St udents',
   'St udents',
   'Colleges',
   'St udents',
   'St udents',
   'St udents'],
  ['Sl.No',
   'Districts',
   'Colleges',
   '',
   'VAi',
   'Total',
   'Colleges',
   '',
   'VAi',
   'Total'],
  ['Sl.No',
   'Districts',
   'Colleges',
   'Boys',
   'Girls',
   'Total',
   'Colleges',
   'Boys',
   'Girls',
   'Total'],
  ['1', '2', '620', '621', '622', '623', '624', '625', '626', '627']],
 [['10.9 Infrastructure Facilities in Primary schools on 30.9.2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 In Nos.'],
  ['', 'ffl', '', '', '', '', ''],
  ['',
   'ffl',
   'InfrastructureFacilitiesinPrimary Schools',
   'InfrastructureFacilitiesinPrimary Schools',
   'InfrastructureFacilitiesinPrimary Schools',
   'InfrastructureFacilitiesinPrimary Schools',
   'InfrastructureFacilitiesinPrimary Schools'],
  ['',
   'ffl',
   'Ramp',
   'Compound',
   'flAi Drinking Wat',
   'fiAi Library',
   'tP Comput'],
  ['1', '2', '586', '587', '588', '589', '590']],
 [['10.13 No. of Medical Colleges and Students edi cal Colleges Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students edi cal Colleges Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students edi cal Colleges Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students edi cal Colleges Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students edi cal Colleges Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students edi cal Colleges Year 2015-16 in Nos.'],
  ['', '.ffl', 'Cfl', 'Cfl', '', ''],
  ['',
   '.ffl',
   'Medical Colleges Allopathy',
   'Medical Colleges Allopathy',
   'Dental Colleges',
   'Dental Colleges'],
  ['',
   '.ffl',
   'Number of Colleges',
   'Students Intake',
   'Number of Colleges',
   'Students Intake'],
  ['1', '2', '628', '629', '630', '631']],
 [['10. Education10.1 terates per 2011 Census',
   '10. Education10.1 terates per 2011 Census',
   '10. Education10.1 terates per 2011 Census',
   '10. Education10.1 terates per 2011 Census',
   '10. Education10.1 terates per 2011 Census',
   '10. Education10.1 terates per 2011 Census',
   '10. Education10.1 terates per 2011 Census',
   '10. Education10.1 terates per 2011 Census',
   '10. Education10.1 terates per 2011 Census',
   '10. Education10.1 terates per 2011 Census',
   '10. Education10.1 terates per 2011 Census'],
  ['Sl. No.',
   'Districts',
   'Literates',
   'Literates',
   'Literates',
   'Literates',
   'Literates',
   'Literates',
   'Literates',
   'Literates',
   'Literates'],
  ['Sl. No.',
   'Districts',
   'Rural',
   'Rural',
   'Rural',
   'Urban',
   'Urban',
   'Urban',
   'Total',
   'Total',
   'Total'],
  ['Sl. No.',
   'Districts',
   'Male',
   'Female',
   'Total',
   'Male',
   'Female',
   'Total',
   'Male',
   'Female',
   'Total'],
  ['1', '2', '534', '535', '536', '537', '538', '539', '540', '541', '542']],
 [['10.2 % Literacy Rate % per 2011 Census',
   '10.2 % Literacy Rate % per 2011 Census',
   '10.2 % Literacy Rate % per 2011 Census',
   '10.2 % Literacy Rate % per 2011 Census',
   '10.2 % Literacy Rate % per 2011 Census',
   '10.2 % Literacy Rate % per 2011 Census',
   '10.2 % Literacy Rate % per 2011 Census',
   '10.2 % Literacy Rate % per 2011 Census',
   '10.2 % Literacy Rate % per 2011 Census',
   '10.2 % Literacy Rate % per 2011 Census',
   '10.2 % Literacy Rate % per 2011 Census',
   '10.2 % Literacy Rate % per 2011 Census'],
  ['',
   '.ffl',
   'Literacyrate',
   'Literacyrate',
   'Literacyrate',
   'Literacyrate',
   'Literacyrate',
   'Literacyrate',
   'Literacyrate',
   'Literacyrate',
   'Literacyrate',
   ''],
  ['',
   '.ffl',
   'Rural',
   'Rural',
   'Rural',
   'Urban',
   'Urban',
   'Urban',
   'Total',
   'Total',
   'Total',
   'Rank'],
  ['',
   '.ffl',
   'Afi Male',
   'Female',
   'Total',
   'Afi Male',
   'Female',
   'Total',
   'Afi Male',
   'Female',
   'Total',
   'Rank'],
  ['1',
   '2',
   '543',
   '544',
   '545',
   '546',
   '547',
   '548',
   '549',
   '550',
   '551',
   '552']],
 [['10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015'],
  ['Sl.No',
   'Districts',
   'Number of Schools',
   'HighSchools',
   'HighSchools',
   'HighSchools'],
  ['Sl.No',
   'Districts',
   'Number of Schools',
   'TotalEnrolment 9-10th standard',
   'TotalEnrolment 9-10th standard',
   'TotalEnrolment 9-10th standard'],
  ['Sl.No', 'Districts', 'Number of Schools', '', 'VAi', 'rls Total'],
  ['1', '2', '561', '562', '563', '564']],
 [['10.10 Infrastructure Facilities in High schools on 30.9.2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 in Nos.'],
  ['Sl.No.', 'Districts', '', '', '', '', ''],
  ['Sl.No.',
   'Districts',
   'Infrastructure Facilities in High Schools',
   'Infrastructure Facilities in High Schools',
   'Infrastructure Facilities in High Schools',
   'Infrastructure Facilities in High Schools',
   'Infrastructure Facilities in High Schools'],
  ['Sl.No.',
   'Districts',
   'No.ofHigh Schools',
   'fiAi Boys Toilet',
   'fiAi Girls Toilet',
   'Electricity',
   'PlayGround'],
  ['1', '2', '591', '592', '593', '594', '595']],
 [['10.8 6 jAz 14 No. of Children in the age group 6 to 14 years and out of schoolYear 2015-16.',
   '10.8 6 jAz 14 No. of Children in the age group 6 to 14 years and out of schoolYear 2015-16.',
   '10.8 6 jAz 14 No. of Children in the age group 6 to 14 years and out of schoolYear 2015-16.',
   '10.8 6 jAz 14 No. of Children in the age group 6 to 14 years and out of schoolYear 2015-16.',
   '10.8 6 jAz 14 No. of Children in the age group 6 to 14 years and out of schoolYear 2015-16.',
   '10.8 6 jAz 14 No. of Children in the age group 6 to 14 years and out of schoolYear 2015-16.',
   '10.8 6 jAz 14 No. of Children in the age group 6 to 14 years and out of schoolYear 2015-16.',
   '10.8 6 jAz 14 No. of Children in the age group 6 to 14 years and out of schoolYear 2015-16.'],
  ['',
   'ffl',
   '6 jAz 14 ASNo.of Children age group between6 to 14',
   '6 jAz 14 ASNo.of Children age group between6 to 14',
   '6 jAz 14 ASNo.of Children age group between6 to 14',
   'jA7z 14 No.ofChildren outofschool agegroupbetween7to14',
   'jA7z 14 No.ofChildren outofschool agegroupbetween7to14',
   'jA7z 14 No.ofChildren outofschool agegroupbetween7to14'],
  ['', 'ffl', 'Boys', 'VAi Girls', 'Total', 'Boys', 'VAi Girls', 'Total'],
  ['1', '2', '575', '576', '577', '578', '579', '580']],
 [['10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015'],
  ['Sl.No.',
   'Districts',
   'ANumber of Schools',
   'jAi LowerPrimarySch',
   'jAi LowerPrimarySch',
   'jAi LowerPrimarySch'],
  ['Sl.No.',
   'Districts',
   'ANumber of Schools',
   'TotalEnrolment 1-5th standard',
   'TotalEnrolment 1-5th standard',
   'TotalEnrolment 1-5th standard'],
  ['Sl.No.', 'Districts', 'ANumber of Schools', '', 'VAs irls', 'Total'],
  ['1', '2', '553', '554', '555', '556']],
 [['10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of Colleges Students and Lecturers Year 2015-16 In Nos'],
  ['Sl.No',
   'Districts',
   'No of Colleges',
   'No. of Lecturers',
   'No. of Lecturers',
   'No.Of Students in colleges 1 2nd Year 1 2',
   'No.Of Students in colleges 1 2nd Year 1 2',
   'No.Of Students in colleges 1 2nd Year 1 2',
   'No.Of Students in colleges 1 2nd Year 1 2',
   'No.Of Students in colleges 1 2nd Year 1 2',
   'No.Of Students in colleges 1 2nd Year 1 2',
   'No.Of Students in colleges 1 2nd Year 1 2',
   'No.Of Students in colleges 1 2nd Year 1 2'],
  ['Sl.No',
   'Districts',
   'No of Colleges',
   'No. of Lecturers',
   'No. of Lecturers',
   'jGovernment',
   'jGovernment',
   'Private',
   'Private',
   'Private',
   'Private',
   'Total Govt Private',
   'Total Govt Private'],
  ['Sl.No',
   'Districts',
   'No of Colleges',
   'No. of Lecturers',
   'No. of Lecturers',
   'jGovernment',
   'jGovernment',
   'Aided',
   'Aided',
   'Unaided',
   'Unaided',
   'Total Govt Private',
   'Total Govt Private'],
  ['Sl.No',
   'Districts',
   'No of Colleges',
   '',
   '',
   '',
   'VAi',
   '',
   'VAi',
   '',
   'VAi',
   '',
   'VAi'],
  ['Sl.No',
   'Districts',
   'No of Colleges',
   'Men',
   'Women',
   'Boys',
   'Girls',
   'Boys',
   'Girls',
   'Boys',
   'Girls',
   'Boys',
   'Girls'],
  ['1',
   '2',
   '601',
   '602',
   '603',
   '604',
   '605',
   '606',
   '607',
   '608',
   '609',
   '610',
   '611']],
 [['10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015'],
  ['',
   'ffl',
   'ANumber of Schools',
   'jAi UpperPrimarySchools Total Enrolment',
   'jAi UpperPrimarySchools Total Enrolment',
   'jAi UpperPrimarySchools Total Enrolment'],
  ['', 'ffl', 'ANumber of Schools', '', 'VAi Gir', 'Total'],
  ['1', '2', '557', '558', '559', '560']],
 [['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos'],
  ['',
   'ffl',
   'General DegreeColleges-Government',
   'General DegreeColleges-Government',
   'General DegreeColleges-Government',
   'General DegreeColleges-Government',
   'General DegreeCollegesPrivate',
   'General DegreeCollegesPrivate',
   'General DegreeCollegesPrivate',
   'General DegreeCollegesPrivate',
   ''],
  ['',
   'ffl',
   'No.ofColleges',
   'CAw Ist yeartofinal year',
   'CAw Ist yeartofinal year',
   'CAw Ist yeartofinal year',
   'No.ofColleges',
   'CAw Istyeartofinalyear aide',
   'CAw Istyeartofinalyear aide',
   'CAw Istyeartofinalyear aide',
   ''],
  ['',
   'ffl',
   'No.ofColleges',
   'Boys',
   'Girls',
   'Total',
   'No.ofColleges',
   'Boys',
   'Girls',
   'Total',
   ''],
  ['1', '2', '612', '613', '614', '615', '616', '617', '618', '619', '']],
 [['10.9 Infrastructure Facilities in Primary schools on 30.9.2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30.9.2015 in Nos.'],
  ['Sl.No', 'Districts', '', '', '', '', ''],
  ['Sl.No',
   'Districts',
   'InfrastructureFacilitiesinPrimary Schools',
   'InfrastructureFacilitiesinPrimary Schools',
   'InfrastructureFacilitiesinPrimary Schools',
   'InfrastructureFacilitiesinPrimary Schools',
   'InfrastructureFacilitiesinPrimary Schools'],
  ['Sl.No',
   'Districts',
   'No.of Primary Schools',
   'Boys Toilet',
   'fiAi Girls Toilet',
   'Electricity',
   'PlayGround'],
  ['1', '2', '581', '582', '583', '584', '585']],
 [['10.10 Infrastructure Facilities in High schools on 30.9.2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30.9.2015 In Nos.'],
  ['', 'ffl', '', '', '', '', ''],
  ['',
   'ffl',
   'InfrastructureFacilitiesin High Schools',
   'InfrastructureFacilitiesin High Schools',
   'InfrastructureFacilitiesin High Schools',
   'InfrastructureFacilitiesin High Schools',
   'InfrastructureFacilitiesin High Schools'],
  ['',
   'ffl',
   'Ramp',
   'Compound',
   'Afli Drinking Watre',
   'fiAi Library',
   'Computer'],
  ['1', '2', '596', '597', '598', '599', '600']],
 [['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16'],
  ['Sl.No',
   'District',
   'Polytechnic- Government',
   'Polytechnic- Government',
   'Polytechnic- Government',
   'Polytechnic- Government',
   'Polytechnic-Private Aided Unaided',
   'Polytechnic-Private Aided Unaided',
   'Polytechnic-Private Aided Unaided',
   'Polytechnic-Private Aided Unaided'],
  ['Sl.No',
   'District',
   'No.of Institutions',
   'Istyea',
   'Istyea',
   'Istyea',
   'No.of Institutions',
   'Istyear',
   'Istyear',
   'Istyear'],
  ['Sl.No',
   'District',
   'No.of Institutions',
   '',
   '',
   '',
   'No.of Institutions',
   '',
   '',
   ''],
  ['Sl.No',
   'District',
   'No.of Institutions',
   'Male',
   'Female',
   'Total',
   'No.of Institutions',
   'Male',
   'Female',
   'Total'],
  ['1', '2', '632', '633', '634', '635', '636', '637', '638', '639']],
 [['10.7 No. of High School Teachers Student Teacher Ratio on 30.9.2015',
   '10.7 No. of High School Teachers Student Teacher Ratio on 30.9.2015',
   '10.7 No. of High School Teachers Student Teacher Ratio on 30.9.2015',
   '10.7 No. of High School Teachers Student Teacher Ratio on 30.9.2015',
   '10.7 No. of High School Teachers Student Teacher Ratio on 30.9.2015',

In [12]:
list_to_remove = [[['10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015'],
  ['Sl.No',
   'Districts',
   'Number of Schools',
   'HighSchools',
   'HighSchools',
   'HighSchools'],
  ['Sl.No',
   'Districts',
   'Number of Schools',
   'TotalEnrolment 9-10th standard',
   'TotalEnrolment 9-10th standard',
   'TotalEnrolment 9-10th standard'],
  ['Sl.No', 'Districts', 'Number of Schools', '', 'VAi', 'rls Total'],
  ['1', '2', '561', '562', '563', '564']],
  [['10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015'],
  ['Sl.No.',
   'Districts',
   'ANumber of Schools',
   'jAi LowerPrimarySch',
   'jAi LowerPrimarySch',
   'jAi LowerPrimarySch'],
  ['Sl.No.',
   'Districts',
   'ANumber of Schools',
   'TotalEnrolment 1-5th standard',
   'TotalEnrolment 1-5th standard',
   'TotalEnrolment 1-5th standard'],
  ['Sl.No.', 'Districts', 'ANumber of Schools', '', 'VAs irls', 'Total'],
  ['1', '2', '553', '554', '555', '556']],
  [['10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015'],
  ['',
   'ffl',
   'ANumber of Schools',
   'jAi UpperPrimarySchools Total Enrolment',
   'jAi UpperPrimarySchools Total Enrolment',
   'jAi UpperPrimarySchools Total Enrolment'],
  ['', 'ffl', 'ANumber of Schools', '', 'VAi Gir', 'Total'],
  ['1', '2', '557', '558', '559', '560']]]

In [13]:
for item in list_to_remove:
    output_list.remove(item)

In [14]:
list_to_add = [[['10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015',
   '10.5 oSf igh Schools and Students on 30.9.2015'],
  ['Sl.No',
   'Districts',
   'Number of Schools',
   'HighSchools',
   'HighSchools',
   'HighSchools'],
  ['Sl.No',
   'Districts',
   'Number of Schools',
   'TotalEnrolment 9-10th standard',
   'TotalEnrolment 9-10th standard',
   'TotalEnrolment 9-10th standard'],
  ['Sl.No', 'Districts', 'Number of Schools', 'Boys', 'Girls', 'Total'],
  ['1', '2', '561', '562', '563', '564']],
  [['10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015',
   '10.3 QjAi No Sof wer Primary Schools and Students Year 2015-16 on 30.9.2015'],
  ['Sl.No.',
   'Districts',
   'ANumber of Schools',
   'jAi LowerPrimarySch',
   'jAi LowerPrimarySch',
   'jAi LowerPrimarySch'],
  ['Sl.No.',
   'Districts',
   'ANumber of Schools',
   'TotalEnrolment 1-5th standard',
   'TotalEnrolment 1-5th standard',
   'TotalEnrolment 1-5th standard'],
  ['Sl.No.', 'Districts', 'ANumber of Schools', 'Boys', 'Girls', 'Total'],
  ['1', '2', '553', '554', '555', '556']],
  [['10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015',
   '10.4 jAi NAo.So Higher Primary Schools and Students on 30.9.2015'],
  ['',
   'ffl',
   'ANumber of Schools',
   'jAi UpperPrimarySchools Total Enrolment',
   'jAi UpperPrimarySchools Total Enrolment',
   'jAi UpperPrimarySchools Total Enrolment'],
  ['', 'ffl', 'ANumber of Schools', 'Boys', 'Girls', 'Total'],
  ['1', '2', '557', '558', '559', '560']]]

output_list.extend(list_to_add)

In [15]:
def add_space_before_year(input_string):
    # Regular expression to find a year in 'yyyy' format with an optional alphabet character before it
    pattern = re.compile(r'([a-zA-Z])?(\d{4})')
    
    # Function to add space between alphabet character and year
    def replace(match):
        alphabet_part, year_part = match.groups()
        if alphabet_part:
            return f'{alphabet_part} {year_part}'
        else:
            return year_part

    # Using re.sub() to apply the replacement function to the input string
    result = pattern.sub(replace, input_string)

    return result

In [16]:
def remove_before_all_occurrence(input_string):
    # Regular expression to match numbers with dot similar to dd.dd, d.d, d.dd, or dd.d
    pattern = re.compile(r'\b(\d\.\d|\d{2}\.\d|\d\.\d{2}|\d{2}\.\d{2})\b')

    # Find all occurrences of the pattern in the input string
    matches = list(pattern.finditer(input_string))

    # If there are at least two occurrences of the pattern, remove everything before the second occurrence
    for i in range(len(matches)):
        second_occurrence_index = matches[i].start()
        input_string = input_string[second_occurrence_index:]

    return input_string.strip()

In [17]:
def convert_uppercase_to_camel_case(input_string):
    words = input_string.split()
    result_words = [word.capitalize() if word.isupper() else word for word in words]
    result_string = ' '.join(result_words)
    return result_string

In [18]:
def add_space_before_camelcase(input_string):
    # Use regular expression to find camel case words
    camelcase_pattern = re.compile(r'(?<=[a-z])(?=[A-Z])')
    result_string = camelcase_pattern.sub(' ', input_string)
    return result_string

In [19]:
def remove_extra_spaces(input_string):
    # Use regular expression to replace consecutive white spaces with a single space
    cleaned_string = re.sub(r'\s+', ' ', input_string)
    return cleaned_string.strip()

In [20]:
def add_space_before_word_with_condition(input_string):
    # Use regular expression to find words preceded by a number or special character
    pattern = re.compile(r'(?<=[%])\b(\w+)\b', flags=re.IGNORECASE)

    # Using re.sub() to add space before matched words
    result_string = pattern.sub(lambda x: ' ' + x.group(1), input_string)

    return result_string

In [21]:
def replace_words_with_blank(input_string, words_to_replace):
    # Constructing a regular expression pattern to match any of the words in the set
    # pattern = re.compile(r'\b(?:' + '|'.join(re.escape(word) for word in words_to_replace) + r')\b', flags=re.IGNORECASE)
    pattern = re.compile(r'(?<!\S)(?:' + '|'.join(re.escape(word) for word in words_to_replace) + r')(?!\S)', flags=re.IGNORECASE)

    # Using re.sub() to replace matched words with blank
    result = pattern.sub('', input_string)

    return result.strip()

In [22]:
words_to_replace = ['QjAi', 'flAi', '30.9.2015', 'iaxled', '2005Dy', 'zPr', 'AUq', 'MAz', 'sfi', 'Raing', 'ema', '.CA', '.Dg', '.G.S', '.Jfl', '.Q.', '.ffl', '1 2', '1-10', '2 01', '2005 jAz 2015', '2006 jAz 2016', '2011 twAi rAi AaP fiU', '2011 twAi zsj wAi EAzs %', '20112.2', '20112.6', '2011g', '24 7', '31.03.2016', '31.3.201', '31.3.2016', '31.3.2016.', '33 jAz 6', '6 jAz 1', '6 jAz 14', '6 wAU', 'A.ffl', 'A.g', 'AdP', 'Adg', 'Affl', 'Afi', 'Afli', 'Aid', 'Arg', 'Azs', 'CAU', 'CAZ', 'CAv', 'CAw', 'CAz', 'Cfi', 'CrP', 'Dfi', 'Dfl', 'E.J .n. .Dg .Jfl .JA.', 'EAf', 'Efi', 'Efl', 'JfiP', 'Jfl', 'KfiQ', 'MlM', 'Pfi', 'QAi', 'Raing', 'Rfl', 'SQA', 'Three', 'VAi', 'dfl', 'eng cy.U', 'ffl', 'fiAi', 'fiP', 'fiQ', 'fiQAi', 'fiU', 'fig', 'fl.', 'gLi', 'gMl', 'jAU', 'jAi', 'lion nit', 'ofD', 'rAi', 'tAwAi', 'tP', 'twAi', 'tzx', 'wAi', 'tzs']

In [23]:
def replace_words(input_string, word_replacements):
    # Constructing a regular expression pattern to match whole words in the set
    # pattern = re.compile(r'\b(?:' + '|'.join(re.escape(word) for word in word_replacements.keys()) + r')\b')
    pattern = re.compile(r'(?<!\S)(?:' + '|'.join(re.escape(word) for word in word_replacements.keys()) + r')(?!\S)')
    
    # Using re.sub() to replace matched words with their corresponding replacements
    result = pattern.sub(lambda x: word_replacements.get(x.group(), x.group()), input_string)

    return result

In [26]:
word_replacements = { "Istyear" : "Ist year", "jIndian" : "Indian", "IndianSystemofMedicine" : "Indian System of Medicine", "yeartofinalyear" : "year to final year", "Istyeartofinalyear" : "Ist year to final year", "tudents" : "Students", "Education10.1 terates" : "10.1 Literates", "teracy" : "Literacy", "Literacyrate" : "Literacy rate", " oSf igh" : "No.of High", "ASNo.of" : "No.of", "between6" : "between 6", "LowerPrimarySch" : "LowerPrimarySchool",  "No Sof wer" : "No.of Lower", "between6" : "between 6", "LecturersG" : "Lecturers", "No.of Colleges" : "No.of P U Colleges", "jGovernment" : "Government", "fiGirls" : "Girls", "yeartofinal" : "year to final", "FacilitiesinPrimary" : "Facilities in Primary", "Drinking Wat" : "Drinking Water", "Comput" : "Computer", "St udents" : "Students", "on" : "on 30-09-2015", "InfrastructureFacilitiesinPrimary" : "Infrastructure Facilities in Primary", "edi cal" : "Medical", "10.2 %" : "10.2", "outofschool" : "out of school", "agegroupbetween7to14" : "age group between 7 to 14", "ANumber" : "Number", "in colleges" : "in PU colleges", "1 2nd Year 1 2" : "1-2nd Year", "NAo.So" : "No.of", "Watre" : "Water", "Istyea" : "Istyear"}

In [27]:
def process_data(input_data):
    for k in range(len(input_data)):
        for i in range(len(input_data[k])):
            for j in range(len(input_data[k][i])):
                #print(k,i,j,input_data[k][i][j])

                input_data[k][i][j] = add_space_before_year(input_data[k][i][j])
                input_data[k][i][j] = replace_words_with_blank(input_data[k][i][j], words_to_replace)
                input_data[k][i][j] = replace_words(input_data[k][i][j], word_replacements)
                input_data[k][i][j] = remove_before_all_occurrence(input_data[k][i][j])
                input_data[k][i][j] = add_space_before_camelcase(input_data[k][i][j])
                input_data[k][i][j] = convert_uppercase_to_camel_case(input_data[k][i][j])
                input_data[k][i][j] = remove_extra_spaces(input_data[k][i][j])
                input_data[k][i][j] = add_space_before_word_with_condition(input_data[k][i][j])

In [28]:
process_data(output_list)
output_list

[[['10.15 No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 No.of Engineering Colleges and Students Year- 2015-16',
   '10.15 No.of Engineering Colleges and Students Year- 2015-16'],
  ['',
   '',
   'Engineering- Government',
   'Engineering- Government',
   'Engineering- Government',
   'Engineering- Government',
   'Engineering- Private Aided',
   'Engineering- Private Aided',
   'Engineering- Private Aided',
   'Engineering- Private Aided'],
  ['',
   '',
   'No.of P U Colleges',
   'Ist year',
   'Ist year',
   'Ist year',
   'No.of P U Colleges',
   'Ist year',
   'Ist year',
   'Ist year'],
  ['', '', 'No.of P U Colleges', '', '', '', 'No.of P U Colleges', '', '', ''],
  ['',
   '',
   'No.of P U Colleges',
   'Male',
   'Female',
   'Total',
   'No.of P U Colleges',
   'Male',
   'Female',
   'Total'],
  ['1', '2', '640', '641', '642', '643', '644', '645', '646', '647']],
 [['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.'],
  ['Sl.No',
   'Districts',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Indian System of Medicine Colleges Government Ist year to final year',
   '',
   '',
   '',
   ''],
  ['Sl.No',
   'Districts',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Indian System of Medicine Colleges Private Ist year to final year aided unaided',
   'Indian System of Medicine Colleges Private Ist year to final year aided unaided',
   'Indian System of Medicine Colleges Private Ist year to final year aided unaided',
   'Indian System of Medicine Colleges Private Ist year to final year aided unaided'],
  ['Sl.No',
   'Districts',
   'Colleges',
   'Students',
   'Students',
   'Students',
   'Colleges',
   'Students',
   'Students',
   'Students'],
  ['Sl.No',
   'Districts',
   'Colleges',
   '',
   '',
   'Total',
   'Colleges',
   '',
   '',
   'Total'],
  ['Sl.No',
   'Districts',
   'Colleges',
   'Boys',
   'Girls',
   'Total',
   'Colleges',
   'Boys',
   'Girls',
   'Total'],
  ['1', '2', '620', '621', '622', '623', '624', '625', '626', '627']],
 [['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.'],
  ['', '', '', '', '', '', ''],
  ['',
   '',
   'Infrastructure Facilities in Primary Schools',
   'Infrastructure Facilities in Primary Schools',
   'Infrastructure Facilities in Primary Schools',
   'Infrastructure Facilities in Primary Schools',
   'Infrastructure Facilities in Primary Schools'],
  ['', '', 'Ramp', 'Compound', 'Drinking Water', 'Library', 'Computer'],
  ['1', '2', '586', '587', '588', '589', '590']],
 [['10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.',
   '10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.'],
  ['', '', 'Cfl', 'Cfl', '', ''],
  ['',
   '',
   'Medical Colleges Allopathy',
   'Medical Colleges Allopathy',
   'Dental Colleges',
   'Dental Colleges'],
  ['',
   '',
   'Number of Colleges',
   'Students Intake',
   'Number of Colleges',
   'Students Intake'],
  ['1', '2', '628', '629', '630', '631']],
 [['10.1 Literates per 2011 Census',
   '10.1 Literates per 2011 Census',
   '10.1 Literates per 2011 Census',
   '10.1 Literates per 2011 Census',
   '10.1 Literates per 2011 Census',
   '10.1 Literates per 2011 Census',
   '10.1 Literates per 2011 Census',
   '10.1 Literates per 2011 Census',
   '10.1 Literates per 2011 Census',
   '10.1 Literates per 2011 Census',
   '10.1 Literates per 2011 Census'],
  ['Sl. No.',
   'Districts',
   'Literates',
   'Literates',
   'Literates',
   'Literates',
   'Literates',
   'Literates',
   'Literates',
   'Literates',
   'Literates'],
  ['Sl. No.',
   'Districts',
   'Rural',
   'Rural',
   'Rural',
   'Urban',
   'Urban',
   'Urban',
   'Total',
   'Total',
   'Total'],
  ['Sl. No.',
   'Districts',
   'Male',
   'Female',
   'Total',
   'Male',
   'Female',
   'Total',
   'Male',
   'Female',
   'Total'],
  ['1', '2', '534', '535', '536', '537', '538', '539', '540', '541', '542']],
 [['10.2 Literacy Rate % per 2011 Census',
   '10.2 Literacy Rate % per 2011 Census',
   '10.2 Literacy Rate % per 2011 Census',
   '10.2 Literacy Rate % per 2011 Census',
   '10.2 Literacy Rate % per 2011 Census',
   '10.2 Literacy Rate % per 2011 Census',
   '10.2 Literacy Rate % per 2011 Census',
   '10.2 Literacy Rate % per 2011 Census',
   '10.2 Literacy Rate % per 2011 Census',
   '10.2 Literacy Rate % per 2011 Census',
   '10.2 Literacy Rate % per 2011 Census',
   '10.2 Literacy Rate % per 2011 Census'],
  ['',
   '',
   'Literacy rate',
   'Literacy rate',
   'Literacy rate',
   'Literacy rate',
   'Literacy rate',
   'Literacy rate',
   'Literacy rate',
   'Literacy rate',
   'Literacy rate',
   ''],
  ['',
   '',
   'Rural',
   'Rural',
   'Rural',
   'Urban',
   'Urban',
   'Urban',
   'Total',
   'Total',
   'Total',
   'Rank'],
  ['',
   '',
   'Male',
   'Female',
   'Total',
   'Male',
   'Female',
   'Total',
   'Male',
   'Female',
   'Total',
   'Rank'],
  ['1',
   '2',
   '543',
   '544',
   '545',
   '546',
   '547',
   '548',
   '549',
   '550',
   '551',
   '552']],
 [['10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.'],
  ['Sl.No.', 'Districts', '', '', '', '', ''],
  ['Sl.No.',
   'Districts',
   'Infrastructure Facilities in High Schools',
   'Infrastructure Facilities in High Schools',
   'Infrastructure Facilities in High Schools',
   'Infrastructure Facilities in High Schools',
   'Infrastructure Facilities in High Schools'],
  ['Sl.No.',
   'Districts',
   'No.of High Schools',
   'Boys Toilet',
   'Girls Toilet',
   'Electricity',
   'Play Ground'],
  ['1', '2', '591', '592', '593', '594', '595']],
 [['10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   '10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   '10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   '10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   '10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   '10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   '10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   '10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.'],
  ['',
   '',
   'No.of Children age group between 6 to 14',
   'No.of Children age group between 6 to 14',
   'No.of Children age group between 6 to 14',
   'j A7z 14 No.of Children out of school age group between 7 to 14',
   'j A7z 14 No.of Children out of school age group between 7 to 14',
   'j A7z 14 No.of Children out of school age group between 7 to 14'],
  ['', '', 'Boys', 'Girls', 'Total', 'Boys', 'Girls', 'Total'],
  ['1', '2', '575', '576', '577', '578', '579', '580']],
 [['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   '10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos'],
  ['Sl.No',
   'Districts',
   'No of Colleges',
   'No. of Lecturers',
   'No. of Lecturers',
   'No.Of Students in Pu colleges 1 2nd Year',
   'No.Of Students in Pu colleges 1 2nd Year',
   'No.Of Students in Pu colleges 1 2nd Year',
   'No.Of Students in Pu colleges 1 2nd Year',
   'No.Of Students in Pu colleges 1 2nd Year',
   'No.Of Students in Pu colleges 1 2nd Year',
   'No.Of Students in Pu colleges 1 2nd Year',
   'No.Of Students in Pu colleges 1 2nd Year'],
  ['Sl.No',
   'Districts',
   'No of Colleges',
   'No. of Lecturers',
   'No. of Lecturers',
   'Government',
   'Government',
   'Private',
   'Private',
   'Private',
   'Private',
   'Total Govt Private',
   'Total Govt Private'],
  ['Sl.No',
   'Districts',
   'No of Colleges',
   'No. of Lecturers',
   'No. of Lecturers',
   'Government',
   'Government',
   'Aided',
   'Aided',
   'Unaided',
   'Unaided',
   'Total Govt Private',
   'Total Govt Private'],
  ['Sl.No',
   'Districts',
   'No of Colleges',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   ''],
  ['Sl.No',
   'Districts',
   'No of Colleges',
   'Men',
   'Women',
   'Boys',
   'Girls',
   'Boys',
   'Girls',
   'Boys',
   'Girls',
   'Boys',
   'Girls'],
  ['1',
   '2',
   '601',
   '602',
   '603',
   '604',
   '605',
   '606',
   '607',
   '608',
   '609',
   '610',
   '611']],
 [['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '10.12 No.of General Degree Colleges and Students 2015-16 In Nos'],
  ['',
   '',
   'General Degree Colleges-Government',
   'General Degree Colleges-Government',
   'General Degree Colleges-Government',
   'General Degree Colleges-Government',
   'General Degree Colleges Private',
   'General Degree Colleges Private',
   'General Degree Colleges Private',
   'General Degree Colleges Private',
   ''],
  ['',
   '',
   'No.of Colleges',
   'Ist year to final year',
   'Ist year to final year',
   'Ist year to final year',
   'No.of Colleges',
   'Ist year to final year aide',
   'Ist year to final year aide',
   'Ist year to final year aide',
   ''],
  ['',
   '',
   'No.of Colleges',
   'Boys',
   'Girls',
   'Total',
   'No.of Colleges',
   'Boys',
   'Girls',
   'Total',
   ''],
  ['1', '2', '612', '613', '614', '615', '616', '617', '618', '619', '']],
 [['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   '10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.'],
  ['Sl.No', 'Districts', '', '', '', '', ''],
  ['Sl.No',
   'Districts',
   'Infrastructure Facilities in Primary Schools',
   'Infrastructure Facilities in Primary Schools',
   'Infrastructure Facilities in Primary Schools',
   'Infrastructure Facilities in Primary Schools',
   'Infrastructure Facilities in Primary Schools'],
  ['Sl.No',
   'Districts',
   'No.of Primary Schools',
   'Boys Toilet',
   'Girls Toilet',
   'Electricity',
   'Play Ground'],
  ['1', '2', '581', '582', '583', '584', '585']],
 [['10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.'],
  ['', '', '', '', '', '', ''],
  ['',
   '',
   'Infrastructure Facilitiesin High Schools',
   'Infrastructure Facilitiesin High Schools',
   'Infrastructure Facilitiesin High Schools',
   'Infrastructure Facilitiesin High Schools',
   'Infrastructure Facilitiesin High Schools'],
  ['', '', 'Ramp', 'Compound', 'Drinking Water', 'Library', 'Computer'],
  ['1', '2', '596', '597', '598', '599', '600']],
 [['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   '10.14 No.of Polytechnic Colleges and Students Year- 2015-16'],
  ['Sl.No',
   'District',
   'Polytechnic- Government',
   'Polytechnic- Government',
   'Polytechnic- Government',
   'Polytechnic- Government',
   'Polytechnic-Private Aided Unaided',
   'Polytechnic-Private Aided Unaided',
   'Polytechnic-Private Aided Unaided',
   'Polytechnic-Private Aided Unaided'],
  ['Sl.No',
   'District',
   'No.of Institutions',
   'Istyear',
   'Istyear',
   'Istyear',
   'No.of Institutions',
   'Ist year',
   'Ist year',
   'Ist year'],
  ['Sl.No',
   'District',
   'No.of Institutions',
   '',
   '',
   '',
   'No.of Institutions',
   '',
   '',
   ''],
  ['Sl.No',
   'District',
   'No.of Institutions',
   'Male',
   'Female',
   'Total',
   'No.of Institutions',
   'Male',
   'Female',
   'Total'],
  ['1', '2', '632', '633', '634', '635', '636', '637', '638', '639']],
 [['10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   '10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   '10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   '10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   '10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   '10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   '10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015'],
  ['Sl.No.',
   'Districts',
   'Number of Total Enrolment',
   'No.of High School Teacher',
   'No.of High School Teacher',
   'No.of High School Teacher',
   'Student Teacher Ratio'],
  ['Sl.No.',
   'Districts',
   'Number of Total Enrolment',
   'Male',
   'Female',
   'Total',
   'Student Teacher Ratio'],
  ['1', '2', '570', '571', '572', '573', '574']],
 [['10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   '10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   '10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   '10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   '10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   '10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   '10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015'],
  ['',
   '',
   'Number of Total',
   'No.of Primary School Teachers',
   'No.of Primary School Teachers',
   'No.of Primary School Teachers',
   'Student Teacher Ratio'],
  ['',
   '',
   'Number of Total',
   'Male',
   'Female',
   'Total',
   'Student Teacher Ratio'],
  ['1', '2', '565', '566', '567', '568', '569']],
 [['10.5 o Sf igh Schools and Students on 30-09-2015',
   '10.5 o Sf igh Schools and Students on 30-09-2015',
   '10.5 o Sf igh Schools and Students on 30-09-2015',
   '10.5 o Sf igh Schools and Students on 30-09-2015',
   '10.5 o Sf igh Schools and Students on 30-09-2015',
   '10.5 o Sf igh Schools and Students on 30-09-2015'],
  ['Sl.No',
   'Districts',
   'Number of Schools',
   'High Schools',
   'High Schools',
   'High Schools'],
  ['Sl.No',
   'Districts',
   'Number of Schools',
   'Total Enrolment 9-10th standard',
   'Total Enrolment 9-10th standard',
   'Total Enrolment 9-10th standard'],
  ['Sl.No', 'Districts', 'Number of Schools', 'Boys', 'Girls', 'Total'],
  ['1', '2', '561', '562', '563', '564']],
 [['10.3 No.of Lower Primary Schools and Students Year 2015-16 on 30-09-2015',
   '10.3 No.of Lower Primary Schools and Students Year 2015-16 on 30-09-2015',
   '10.3 No.of Lower Primary Schools and Students Year 2015-16 on 30-09-2015',
   '10.3 No.of Lower Primary Schools and Students Year 2015-16 on 30-09-2015',
   '10.3 No.of Lower Primary Schools and Students Year 2015-16 on 30-09-2015',
   '10.3 No.of Lower Primary Schools and Students Year 2015-16 on 30-09-2015'],
  ['Sl.No.',
   'Districts',

In [29]:
#transpose the inner list
transp_list = [[list(pair) for pair in zip(*sublist)] for sublist in output_list]
transp_list

[[['10.15 No.of Engineering Colleges and Students Year- 2015-16',
   '',
   '',
   '',
   '',
   '1'],
  ['10.15 No.of Engineering Colleges and Students Year- 2015-16',
   '',
   '',
   '',
   '',
   '2'],
  ['10.15 No.of Engineering Colleges and Students Year- 2015-16',
   'Engineering- Government',
   'No.of P U Colleges',
   'No.of P U Colleges',
   'No.of P U Colleges',
   '640'],
  ['10.15 No.of Engineering Colleges and Students Year- 2015-16',
   'Engineering- Government',
   'Ist year',
   '',
   'Male',
   '641'],
  ['10.15 No.of Engineering Colleges and Students Year- 2015-16',
   'Engineering- Government',
   'Ist year',
   '',
   'Female',
   '642'],
  ['10.15 No.of Engineering Colleges and Students Year- 2015-16',
   'Engineering- Government',
   'Ist year',
   '',
   'Total',
   '643'],
  ['10.15 No.of Engineering Colleges and Students Year- 2015-16',
   'Engineering- Private Aided',
   'No.of P U Colleges',
   'No.of P U Colleges',
   'No.of P U Colleges',
   '644'],
  ['10.15 No.of Engineering Colleges and Students Year- 2015-16',
   'Engineering- Private Aided',
   'Ist year',
   '',
   'Male',
   '645'],
  ['10.15 No.of Engineering Colleges and Students Year- 2015-16',
   'Engineering- Private Aided',
   'Ist year',
   '',
   'Female',
   '646'],
  ['10.15 No.of Engineering Colleges and Students Year- 2015-16',
   'Engineering- Private Aided',
   'Ist year',
   '',
   'Total',
   '647']],
 [['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   'Sl.No',
   'Sl.No',
   'Sl.No',
   'Sl.No',
   'Sl.No',
   '1'],
  ['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   'Districts',
   'Districts',
   'Districts',
   'Districts',
   'Districts',
   '2'],
  ['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Colleges',
   'Colleges',
   'Colleges',
   '620'],
  ['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Students',
   '',
   'Boys',
   '621'],
  ['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Students',
   '',
   'Girls',
   '622'],
  ['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Indian System of Medicine Colleges Government Ist year to final year',
   'Students',
   'Total',
   'Total',
   '623'],
  ['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '',
   'Indian System of Medicine Colleges Private Ist year to final year aided unaided',
   'Colleges',
   'Colleges',
   'Colleges',
   '624'],
  ['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '',
   'Indian System of Medicine Colleges Private Ist year to final year aided unaided',
   'Students',
   '',
   'Boys',
   '625'],
  ['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '',
   'Indian System of Medicine Colleges Private Ist year to final year aided unaided',
   'Students',
   '',
   'Girls',
   '626'],
  ['10.13 No. of Medical Colleges and Students Year 2015-16 in Nos.',
   '',
   'Indian System of Medicine Colleges Private Ist year to final year aided unaided',
   'Students',
   'Total',
   'Total',
   '627']],
 [['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '',
   '',
   '',
   '1'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '',
   '',
   '',
   '2'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '',
   'Infrastructure Facilities in Primary Schools',
   'Ramp',
   '586'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '',
   'Infrastructure Facilities in Primary Schools',
   'Compound',
   '587'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '',
   'Infrastructure Facilities in Primary Schools',
   'Drinking Water',
   '588'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '',
   'Infrastructure Facilities in Primary Schools',
   'Library',
   '589'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 In Nos.',
   '',
   'Infrastructure Facilities in Primary Schools',
   'Computer',
   '590']],
 [['10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.',
   '',
   '',
   '',
   '1'],
  ['10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.',
   '',
   '',
   '',
   '2'],
  ['10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.',
   'Cfl',
   'Medical Colleges Allopathy',
   'Number of Colleges',
   '628'],
  ['10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.',
   'Cfl',
   'Medical Colleges Allopathy',
   'Students Intake',
   '629'],
  ['10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.',
   '',
   'Dental Colleges',
   'Number of Colleges',
   '630'],
  ['10.13 No. of Medical Colleges and Students Medical Colleges Year 2015-16 in Nos.',
   '',
   'Dental Colleges',
   'Students Intake',
   '631']],
 [['10.1 Literates per 2011 Census', 'Sl. No.', 'Sl. No.', 'Sl. No.', '1'],
  ['10.1 Literates per 2011 Census',
   'Districts',
   'Districts',
   'Districts',
   '2'],
  ['10.1 Literates per 2011 Census', 'Literates', 'Rural', 'Male', '534'],
  ['10.1 Literates per 2011 Census', 'Literates', 'Rural', 'Female', '535'],
  ['10.1 Literates per 2011 Census', 'Literates', 'Rural', 'Total', '536'],
  ['10.1 Literates per 2011 Census', 'Literates', 'Urban', 'Male', '537'],
  ['10.1 Literates per 2011 Census', 'Literates', 'Urban', 'Female', '538'],
  ['10.1 Literates per 2011 Census', 'Literates', 'Urban', 'Total', '539'],
  ['10.1 Literates per 2011 Census', 'Literates', 'Total', 'Male', '540'],
  ['10.1 Literates per 2011 Census', 'Literates', 'Total', 'Female', '541'],
  ['10.1 Literates per 2011 Census', 'Literates', 'Total', 'Total', '542']],
 [['10.2 Literacy Rate % per 2011 Census', '', '', '', '1'],
  ['10.2 Literacy Rate % per 2011 Census', '', '', '', '2'],
  ['10.2 Literacy Rate % per 2011 Census',
   'Literacy rate',
   'Rural',
   'Male',
   '543'],
  ['10.2 Literacy Rate % per 2011 Census',
   'Literacy rate',
   'Rural',
   'Female',
   '544'],
  ['10.2 Literacy Rate % per 2011 Census',
   'Literacy rate',
   'Rural',
   'Total',
   '545'],
  ['10.2 Literacy Rate % per 2011 Census',
   'Literacy rate',
   'Urban',
   'Male',
   '546'],
  ['10.2 Literacy Rate % per 2011 Census',
   'Literacy rate',
   'Urban',
   'Female',
   '547'],
  ['10.2 Literacy Rate % per 2011 Census',
   'Literacy rate',
   'Urban',
   'Total',
   '548'],
  ['10.2 Literacy Rate % per 2011 Census',
   'Literacy rate',
   'Total',
   'Male',
   '549'],
  ['10.2 Literacy Rate % per 2011 Census',
   'Literacy rate',
   'Total',
   'Female',
   '550'],
  ['10.2 Literacy Rate % per 2011 Census',
   'Literacy rate',
   'Total',
   'Total',
   '551'],
  ['10.2 Literacy Rate % per 2011 Census', '', 'Rank', 'Rank', '552']],
 [['10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   'Sl.No.',
   'Sl.No.',
   'Sl.No.',
   '1'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   'Districts',
   'Districts',
   'Districts',
   '2'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   '',
   'Infrastructure Facilities in High Schools',
   'No.of High Schools',
   '591'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   '',
   'Infrastructure Facilities in High Schools',
   'Boys Toilet',
   '592'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   '',
   'Infrastructure Facilities in High Schools',
   'Girls Toilet',
   '593'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   '',
   'Infrastructure Facilities in High Schools',
   'Electricity',
   '594'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 in Nos.',
   '',
   'Infrastructure Facilities in High Schools',
   'Play Ground',
   '595']],
 [['10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   '',
   '',
   '1'],
  ['10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   '',
   '',
   '2'],
  ['10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   'No.of Children age group between 6 to 14',
   'Boys',
   '575'],
  ['10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   'No.of Children age group between 6 to 14',
   'Girls',
   '576'],
  ['10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   'No.of Children age group between 6 to 14',
   'Total',
   '577'],
  ['10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   'j A7z 14 No.of Children out of school age group between 7 to 14',
   'Boys',
   '578'],
  ['10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   'j A7z 14 No.of Children out of school age group between 7 to 14',
   'Girls',
   '579'],
  ['10.8 No. of Children in the age group 6 to 14 years and out of school Year 2015-16.',
   'j A7z 14 No.of Children out of school age group between 7 to 14',
   'Total',
   '580']],
 [['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'Sl.No',
   'Sl.No',
   'Sl.No',
   'Sl.No',
   'Sl.No',
   '1'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'Districts',
   'Districts',
   'Districts',
   'Districts',
   'Districts',
   '2'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'No of Colleges',
   'No of Colleges',
   'No of Colleges',
   'No of Colleges',
   'No of Colleges',
   '601'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'No. of Lecturers',
   'No. of Lecturers',
   'No. of Lecturers',
   '',
   'Men',
   '602'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'No. of Lecturers',
   'No. of Lecturers',
   'No. of Lecturers',
   '',
   'Women',
   '603'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'No.Of Students in Pu colleges 1 2nd Year',
   'Government',
   'Government',
   '',
   'Boys',
   '604'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'No.Of Students in Pu colleges 1 2nd Year',
   'Government',
   'Government',
   '',
   'Girls',
   '605'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'No.Of Students in Pu colleges 1 2nd Year',
   'Private',
   'Aided',
   '',
   'Boys',
   '606'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'No.Of Students in Pu colleges 1 2nd Year',
   'Private',
   'Aided',
   '',
   'Girls',
   '607'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'No.Of Students in Pu colleges 1 2nd Year',
   'Private',
   'Unaided',
   '',
   'Boys',
   '608'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'No.Of Students in Pu colleges 1 2nd Year',
   'Private',
   'Unaided',
   '',
   'Girls',
   '609'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'No.Of Students in Pu colleges 1 2nd Year',
   'Total Govt Private',
   'Total Govt Private',
   '',
   'Boys',
   '610'],
  ['10.11 No.of P U Colleges Students and Lecturers Year 2015-16 In Nos',
   'No.Of Students in Pu colleges 1 2nd Year',
   'Total Govt Private',
   'Total Govt Private',
   '',
   'Girls',
   '611']],
 [['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '',
   '',
   '',
   '1'],
  ['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '',
   '',
   '',
   '2'],
  ['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   'General Degree Colleges-Government',
   'No.of Colleges',
   'No.of Colleges',
   '612'],
  ['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   'General Degree Colleges-Government',
   'Ist year to final year',
   'Boys',
   '613'],
  ['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   'General Degree Colleges-Government',
   'Ist year to final year',
   'Girls',
   '614'],
  ['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   'General Degree Colleges-Government',
   'Ist year to final year',
   'Total',
   '615'],
  ['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   'General Degree Colleges Private',
   'No.of Colleges',
   'No.of Colleges',
   '616'],
  ['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   'General Degree Colleges Private',
   'Ist year to final year aide',
   'Boys',
   '617'],
  ['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   'General Degree Colleges Private',
   'Ist year to final year aide',
   'Girls',
   '618'],
  ['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   'General Degree Colleges Private',
   'Ist year to final year aide',
   'Total',
   '619'],
  ['10.12 No.of General Degree Colleges and Students 2015-16 In Nos',
   '',
   '',
   '',
   '']],
 [['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   'Sl.No',
   'Sl.No',
   'Sl.No',
   '1'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   'Districts',
   'Districts',
   'Districts',
   '2'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   '',
   'Infrastructure Facilities in Primary Schools',
   'No.of Primary Schools',
   '581'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   '',
   'Infrastructure Facilities in Primary Schools',
   'Boys Toilet',
   '582'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   '',
   'Infrastructure Facilities in Primary Schools',
   'Girls Toilet',
   '583'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   '',
   'Infrastructure Facilities in Primary Schools',
   'Electricity',
   '584'],
  ['10.9 Infrastructure Facilities in Primary schools on 30-09-2015 in Nos.',
   '',
   'Infrastructure Facilities in Primary Schools',
   'Play Ground',
   '585']],
 [['10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '',
   '',
   '',
   '1'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '',
   '',
   '',
   '2'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '',
   'Infrastructure Facilitiesin High Schools',
   'Ramp',
   '596'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '',
   'Infrastructure Facilitiesin High Schools',
   'Compound',
   '597'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '',
   'Infrastructure Facilitiesin High Schools',
   'Drinking Water',
   '598'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '',
   'Infrastructure Facilitiesin High Schools',
   'Library',
   '599'],
  ['10.10 Infrastructure Facilities in High schools on 30-09-2015 In Nos.',
   '',
   'Infrastructure Facilitiesin High Schools',
   'Computer',
   '600']],
 [['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   'Sl.No',
   'Sl.No',
   'Sl.No',
   'Sl.No',
   '1'],
  ['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   'District',
   'District',
   'District',
   'District',
   '2'],
  ['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   'Polytechnic- Government',
   'No.of Institutions',
   'No.of Institutions',
   'No.of Institutions',
   '632'],
  ['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   'Polytechnic- Government',
   'Istyear',
   '',
   'Male',
   '633'],
  ['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   'Polytechnic- Government',
   'Istyear',
   '',
   'Female',
   '634'],
  ['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   'Polytechnic- Government',
   'Istyear',
   '',
   'Total',
   '635'],
  ['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   'Polytechnic-Private Aided Unaided',
   'No.of Institutions',
   'No.of Institutions',
   'No.of Institutions',
   '636'],
  ['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   'Polytechnic-Private Aided Unaided',
   'Ist year',
   '',
   'Male',
   '637'],
  ['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   'Polytechnic-Private Aided Unaided',
   'Ist year',
   '',
   'Female',
   '638'],
  ['10.14 No.of Polytechnic Colleges and Students Year- 2015-16',
   'Polytechnic-Private Aided Unaided',
   'Ist year',
   '',
   'Total',
   '639']],
 [['10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   'Sl.No.',
   'Sl.No.',
   '1'],
  ['10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   'Districts',
   'Districts',
   '2'],
  ['10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   'Number of Total Enrolment',
   'Number of Total Enrolment',
   '570'],
  ['10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   'No.of High School Teacher',
   'Male',
   '571'],
  ['10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   'No.of High School Teacher',
   'Female',
   '572'],
  ['10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   'No.of High School Teacher',
   'Total',
   '573'],
  ['10.7 No. of High School Teachers Student Teacher Ratio on 30-09-2015',
   'Student Teacher Ratio',
   'Student Teacher Ratio',
   '574']],
 [['10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   '',
   '',
   '1'],
  ['10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   '',
   '',
   '2'],
  ['10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   'Number of Total',
   'Number of Total',
   '565'],
  ['10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   'No.of Primary School Teachers',
   'Male',
   '566'],
  ['10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   'No.of Primary School Teachers',
   'Female',
   '567'],
  ['10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   'No.of Primary School Teachers',
   'Total',
   '568'],
  ['10.6 No. of Primar School Teachers Student Teacher Ratio on 30-09-2015',
   'Student Teacher Ratio',
   'Student Teacher Ratio',
   '569']],
 [['10.5 o Sf igh Schools and Students on 30-09-2015',
   'Sl.No',
   'Sl.No',
   'Sl.No',
   '1'],
  ['10.5 o Sf igh Schools and Students on 30-09-2015',
   'Districts',
   'Districts',
   'Districts',
   '2'],
  ['10.5 o Sf igh Schools and Students on 30-09-2015',
   'Number of Schools',
   'Number of Schools',
   'Number of Schools',
   '561'],
  ['10.5 o Sf igh Schools and Students on 30-09-2015',
   'High Schools',
   'Total Enrolment 9-10th standard',
   'Boys',
   '562'],
  ['10.5 o Sf igh Schools and Students on 30-09-2015',
   'High Schools',
   'Total Enrolment 9-10th standard',
   'Girls',
   '563'],
  ['10.5 o Sf igh Schools and Students on 30-09-2015',
   'High Schools',
   'Total Enrolment 9-10th standard',
   'Total',
   '564']],
 [['10.3 No.of Lower Primary Schools and Students Year 2015-16 on 30-09-2015',
   'Sl.No.',
   'Sl.No.',
   'Sl.No.',
   '1'],

In [30]:
def find_table_details(input_string):
    # Regular expression to match numbers with dot similar to dd.dd, d.d, d.dd, or dd.d
    pattern = re.compile(r'\b(\d\.\d|\d{2}\.\d|\d\.\d{2}|\d{2}\.\d{2})\b')

    # Find all occurrences of the pattern in the input string
    matches = pattern.finditer(input_string)

    # Initialize variables to store the matches
    match_positions = []

    # Store the positions of the matches
    for match in matches:
        match_positions.append(match.start())

    # If there is at least one occurrence of the pattern
    if match_positions:
        table_id_index = match_positions[0]
        input_string = input_string[table_id_index:]  
        space_index = input_string.find(' ') 
        table_id = input_string[table_id_index:space_index].strip()
        table_name = input_string[space_index:].strip()
        return table_id, table_name    
    else:
        return None, None

In [31]:
def convert_to_number(string):
    try:
        number = int(string)
    except ValueError:
        try:
            number = float(string)
        except ValueError:
            raise ValueError("Input string is not a valid number")
    return number

In [32]:
chapter_id = 10
chapter_name = "Education"
#processing each column
def process_dictionary(input_data):
    df = pd.DataFrame(columns = ['Attr_id', 'Chapter_id', 'Chapter_name', 'Table_id', 'Table_name', 'Description'])
    for inner_list in input_data:
        table_id, table_name = find_table_details(inner_list[0][0])
        previd=0
        for data_list in inner_list:
            i=0
            attr_id=0
            description = ''
            prev = ''
            for data in reversed(data_list):
                if data == '1' or data == '2':
                    break
                i = i+1;
                if i == 1 and data!='' and (previd==0 or convert_to_number(data)!=previd):
                    attr_id = convert_to_number(data)
                    previd = convert_to_number(data)
                if i > 1 and i < len(data_list):
                    if description == '':
                        description = data
                        prev = data
                    else : 
                        if prev != data and data!='':
                            description = ','.join([description, data]) #description + ' ' + data
                            prev = data
            if attr_id != 0 and description != "" :
                row = {'Attr_id' : attr_id, 'Chapter_id' : chapter_id, 'Chapter_name' : chapter_name, 'Table_id' : table_id, 'Table_name' : table_name, 'Description' : remove_extra_spaces(description)}
                df.loc[len(df)] = row
    df = df.sort_values(by=['Attr_id'])
    df.to_csv(absolute_result_path, sep=';', index=False)
    df.to_csv(absolute_dictionary_path, sep=';', index=False)

In [33]:
process_dictionary(transp_list)