# Extracting table header as list

In [1]:
import collections
collections.Callable = collections.abc.Callable

In [2]:
from bs4 import BeautifulSoup, NavigableString
from html_table_extractor.extractor import Extractor
import pandas as pd
import os
import re

In [3]:
relative_path_html = "../HTML/Output_html_Chapter5/kaggle/working/out/output/"
relative_path_pdf = "../HTML/Output_html_Chapter5/kaggle/working/out/pages/"
relative_dictionary_path = "../Dictionary/Chapter5_Attributes.csv"
relative_result_path = "../HTML/Output_html_Chapter5/Chapter5_Attributes.csv"
# Get the absolute path by joining the current directory with the relative path
absolute_path_html = os.path.join(os.getcwd(), relative_path_html)
absolute_path_pdf = os.path.join(os.getcwd(), relative_path_pdf)
absolute_dictionary_path = os.path.join(os.getcwd(), relative_dictionary_path)
absolute_result_path = os.path.join(os.getcwd(), relative_result_path)

In [4]:
absolute_path_html

'/home/riya/Downloads/ADT/2015-16/Processing_Files/../HTML/Output_html_Chapter5/kaggle/working/out/output/'

In [5]:
os.listdir(absolute_path_html)

['output_page_1.html',
 'output_page_2.html',
 'output_page_5.html',
 'output_page_3.html',
 'output_page_4.html',
 'output_page_7.html',
 'output_page_6.html']

In [6]:
output_list = []

In [7]:
output_list

[]

In [8]:
allowed_two_letter_words = {'sl','sc', 'st', 'cc', 'tp', 'tb', 'ts', 'tg', 'km', 'gm', 'an', 'at', 'by', 'do', 'go', 'if', 'in', 'is', 'it', 'me', 'my', 'no', 'of', 'on', 'or', 'so', 'to', 'up', 'us'}

def replace_td_content(tag):
    if isinstance(tag, NavigableString):
        return  # Skip strings, as they don't have 'contents'

    if tag.name == 'td':
        # Extract only meaningful English words and numbers
        valid_characters = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-.%")
        filtered_content = ''.join(char if char in valid_characters else ' ' for char in tag.get_text())
        
        # Remove extra spaces and words with less than 3 characters
        cleaned_content = ' '.join(word for word in filtered_content.split() if len(word) >= 3 or word.isdigit() or word.lower() in allowed_two_letter_words or word=='%')
        
        # Set the cleaned content as the tag's string
        tag.string = cleaned_content
    elif tag.contents:
        for child in tag.contents:
            replace_td_content(child)

In [9]:
def process_table_cells(target_table):
    if not target_table:
        print("Table not found in the HTML content.")
        return

    flag1 = 0
    flag2 = 0

    # Loop through each row in the table
    for row in target_table.find_all('tr'):
        # Loop through each cell in the row
        if(flag1 == 1 and flag2 == 1):
            row.decompose()
        else : 
            for cell in row.find_all(['td', 'th']):
                # Process the cell content (you can modify this part based on your requirements)
                cell_content = cell.get_text(strip=True)
                if(cell_content == '1'):
                    flag1 = 1
                if(cell_content == '2'):
                    flag2 = 1

In [10]:
# iterate through all file 
for file in os.listdir(absolute_path_html): 
    # Check whether file is in text format or not 
    if file.endswith(".html"): 
        file_path = os.path.join(absolute_path_html, file)
        with open(file_path) as fp:
            soup = BeautifulSoup(fp, "html.parser")
            
            for tag in soup.find_all(attrs={'style': True}):
                tag.attrs.pop('style')
            
            table_tag = soup.find('table')
            
            if table_tag is not None:
                replace_td_content(table_tag)

                process_table_cells(table_tag)

                extractor1 = Extractor(table_tag)
                extractor1.parse()
                output_list.append(extractor1.return_list())
            else:
                print(file_path)

In [11]:
output_list

[[['AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos',
   'AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos',
   'AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos',
   'AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos',
   'AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos',
   'AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos',
   'AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos',
   'AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos',
   'AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos',
   'AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos',
   'AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos',
   'AnimalHusbandry5.1 2012 Livestock Census 2012 In Nos'],
  ['',
   'ffl',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012'],
  ['',
   'ffl',
   'Cattle',
   'Cattle',
   'Cattle',
   'Cattle',
   'Buffaloes',
   'heeps',
   'heeps',
   'heeps',
   'heeps',
   ''],
  ['',
   'ffl',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total',
   'Buffaloes',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total',
   ''],
  ['1',
   '2',
   '351',
   '352',
   '353',
   '354',
   '355',
   '356',
   '357',
   '358',
   '359',
   '']],
 [['5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012'],
  ['Sl.No.',
   'District',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012'],
  ['Sl.No.', 'District', 'Goats', 'Pigs', 'Pigs', 'Pigs', 'Pigs'],
  ['Sl.No.',
   'District',
   'Goats',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total'],
  ['1', '2', '360', '361', '362', '363', '364']],
 [['5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16'],
  ['',
   'ffl',
   'Artificial InseminationDone Numbers',
   'No.of animals treated',
   'Productionof Milk in Thousand Tonnes',
   'Productionof Eggs. inLakhs Nos',
   'MeatProduction inTonnes'],
  ['1', '2', '377', '378', '379', '380', '381']],
 [['5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012'],
  ['',
   'ffl',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012'],
  ['', 'ffl', 'Rabbits', 'Dogs', 'Others', 'TotalLiveStock', 'Poultry'],
  ['1', '2', '365', '366', '367', '368', '369']],
 [['5.2 eterinary Hospitals on 31.3.2016 In Nos.',
   '5.2 eterinary Hospitals on 31.3.2016 In Nos.',
   '5.2 eterinary Hospitals on 31.3.2016 In Nos.',
   '5.2 eterinary Hospitals on 31.3.2016 In Nos.',
   '5.2 eterinary Hospitals on 31.3.2016 In Nos.',
   '5.2 eterinary Hospitals on 31.3.2016 In Nos.',
   '5.2 eterinary Hospitals on 31.3.2016 In Nos.',
   '5.2 eterinary Hospitals on 31.3.2016 In Nos.',
   '5.2 eterinary Hospitals on 31.3.2016 In Nos.'],
  ['Sl.No',
   'District',
   'erinary Institutions',
   'erinary Institutions',
   'erinary Institutions',
   'erinary Institutions',
   'erinary Institutions',
   'erinary Institutions',
   'erinary Institutions'],
  ['Sl.No',
   'District',
   'Veterinary Hospitals KVS',
   'Dispensaries',
   'Primary Veterinary Centres',
   'fiAi Mobile Dispensaries',
   'Artificial InseminationCentres',
   'Others',
   'Total'],
  ['1', '2', '370', '371', '372', '373', '374', '375', '376']],
 [['5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16'],
  ['',
   'ffl',
   'Families involved in fisheries',
   'Families involved in fisheries',
   'No.of Beneficiaries under Mathsasrayascheme',
   'fiP Fish lets In lakhs',
   'Fish markets No'],
  ['',
   'ffl',
   'Full Time',
   'Part Time',
   'No.of Beneficiaries under Mathsasrayascheme',
   'fiP Fish lets In lakhs',
   'Fish markets No'],
  ['1', '2', '389', '390', '391', '392', '393']],
 [['5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016'],
  ['Sl.No.',
   'District',
   'Fish catch in tonnes',
   'Ice Plants',
   'Ice Plants',
   'Cold storages',
   'Cold storages',
   'Total tanks for fisheries',
   'Total tanks for fisheries'],
  ['Sl.No.',
   'District',
   'Fish catch in tonnes',
   'No.',
   'Capacity Tonnes day',
   'No.',
   'Capacity Tonnes',
   'A.g Panchayat Raj',
   'Minor Irrigation'],
  ['1', '2', '382', '383', '384', '385', '386', '387', '388']]]

In [12]:
def add_space_before_year(input_string):
    # Regular expression to find a year in 'yyyy' format with an optional alphabet character before it
    pattern = re.compile(r'([a-zA-Z])?(\d{4})')
    
    # Function to add space between alphabet character and year
    def replace(match):
        alphabet_part, year_part = match.groups()
        if alphabet_part:
            return f'{alphabet_part} {year_part}'
        else:
            return year_part

    # Using re.sub() to apply the replacement function to the input string
    result = pattern.sub(replace, input_string)

    return result

In [13]:
def remove_before_all_occurrence(input_string):
    # Regular expression to match numbers with dot similar to dd.dd, d.d, d.dd, or dd.d
    pattern = re.compile(r'\b(\d\.\d|\d{2}\.\d|\d\.\d{2}|\d{2}\.\d{2})\b')

    # Find all occurrences of the pattern in the input string
    matches = list(pattern.finditer(input_string))

    # If there are at least two occurrences of the pattern, remove everything before the second occurrence
    for i in range(len(matches)):
        second_occurrence_index = matches[i].start()
        input_string = input_string[second_occurrence_index:]

    return input_string.strip()

In [14]:
def convert_uppercase_to_camel_case(input_string):
    words = input_string.split()
    result_words = [word.capitalize() if word.isupper() else word for word in words]
    result_string = ' '.join(result_words)
    return result_string

In [15]:
def add_space_before_camelcase(input_string):
    # Use regular expression to find camel case words
    camelcase_pattern = re.compile(r'(?<=[a-z])(?=[A-Z])')
    result_string = camelcase_pattern.sub(' ', input_string)
    return result_string

In [16]:
def remove_extra_spaces(input_string):
    # Use regular expression to replace consecutive white spaces with a single space
    cleaned_string = re.sub(r'\s+', ' ', input_string)
    return cleaned_string.strip()

In [17]:
def add_space_before_word_with_condition(input_string):
    # Use regular expression to find words preceded by a number or special character
    pattern = re.compile(r'(?<=[%])\b(\w+)\b', flags=re.IGNORECASE)

    # Using re.sub() to add space before matched words
    result_string = pattern.sub(lambda x: ' ' + x.group(1), input_string)

    return result_string

In [18]:
def replace_words_with_blank(input_string, words_to_replace):
    # Constructing a regular expression pattern to match any of the words in the set
    # pattern = re.compile(r'\b(?:' + '|'.join(re.escape(word) for word in words_to_replace) + r')\b', flags=re.IGNORECASE)
    pattern = re.compile(r'(?<!\S)(?:' + '|'.join(re.escape(word) for word in words_to_replace) + r')(?!\S)', flags=re.IGNORECASE)

    # Using re.sub() to replace matched words with blank
    result = pattern.sub('', input_string)

    return result.strip()

In [19]:
words_to_replace = ['Raing', 'ema', '201', '.CA', '.Dg', '.G.S', '.Jfl', '.Q.', '.ffl', '1 2', '1-10', '2 01', '2005 jAz 2015', '2006 jAz 2016', '2011 twAi rAi AaP fiU', '2011 twAi zsj wAi EAzs %', '20112.2', '20112.6', '2011g', '24 7', '31.03.2016', '31.3.201', '31.3.2016', '31.3.2016.', '33 jAz 6', '6 jAz 1', '6 jAz 14', '6 wAU', 'A.ffl', 'A.g', 'AdP', 'Adg', 'Affl', 'Afi', 'Afli', 'Aid', 'Arg', 'Azs', 'CAU', 'CAZ', 'CAv', 'CAw', 'CAz', 'Cfi', 'CrP', 'Dfi', 'Dfl', 'E.J .n. .Dg .Jfl .JA.', 'EAf', 'Efi', 'Efl', 'JfiP', 'Jfl', 'KfiQ', 'MlM', 'Pfi', 'QAi', 'Raing', 'Rfl', 'SQA', 'Three', 'VAi', 'dfl', 'eng cy.U', 'ffl', 'fiAi', 'fiP', 'fiQ', 'fiQAi', 'fiU', 'fig', 'fl.', 'gLi', 'gMl', 'jAU', 'jAi', 'lion nit', 'ofD', 'rAi', 'tAwAi', 'tP', 'twAi', 'tzx', 'wAi', 'tzs']

In [20]:
def replace_words(input_string, word_replacements):
    # Constructing a regular expression pattern to match whole words in the set
    # pattern = re.compile(r'\b(?:' + '|'.join(re.escape(word) for word in word_replacements.keys()) + r')\b')
    pattern = re.compile(r'(?<!\S)(?:' + '|'.join(re.escape(word) for word in word_replacements.keys()) + r')(?!\S)')
    
    # Using re.sub() to replace matched words with their corresponding replacements
    result = pattern.sub(lambda x: word_replacements.get(x.group(), x.group()), input_string)

    return result

In [21]:
word_replacements = { "AnimalHusbandry5.1 2012" : "AnimalHusbandry 5.1", "2012 Livestock" : "Livestock", "Productionof" : "Production of", "on" : "on 31-03-2016", "erinary" : "Veterinary", "KVS" : "KVS/RL" }

In [22]:
def process_data(input_data):
    for k in range(len(input_data)):
        for i in range(len(input_data[k])):
            for j in range(len(input_data[k][i])):
                #print(k,i,j,input_data[k][i][j])

                input_data[k][i][j] = add_space_before_year(input_data[k][i][j])
                input_data[k][i][j] = replace_words_with_blank(input_data[k][i][j], words_to_replace)
                input_data[k][i][j] = replace_words(input_data[k][i][j], word_replacements)
                input_data[k][i][j] = remove_before_all_occurrence(input_data[k][i][j])
                input_data[k][i][j] = add_space_before_camelcase(input_data[k][i][j])
                input_data[k][i][j] = convert_uppercase_to_camel_case(input_data[k][i][j])
                input_data[k][i][j] = remove_extra_spaces(input_data[k][i][j])
                input_data[k][i][j] = add_space_before_word_with_condition(input_data[k][i][j])

In [23]:
process_data(output_list)
output_list

[[['5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos'],
  ['',
   '',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012'],
  ['',
   '',
   'Cattle',
   'Cattle',
   'Cattle',
   'Cattle',
   'Buffaloes',
   'heeps',
   'heeps',
   'heeps',
   'heeps',
   ''],
  ['',
   '',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total',
   'Buffaloes',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total',
   ''],
  ['1',
   '2',
   '351',
   '352',
   '353',
   '354',
   '355',
   '356',
   '357',
   '358',
   '359',
   '']],
 [['5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012'],
  ['Sl.No.',
   'District',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012'],
  ['Sl.No.', 'District', 'Goats', 'Pigs', 'Pigs', 'Pigs', 'Pigs'],
  ['Sl.No.',
   'District',
   'Goats',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total'],
  ['1', '2', '360', '361', '362', '363', '364']],
 [['5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16',
   '5.3 Artificial Insemination and Dairy Production Year 2015-16'],
  ['',
   '',
   'Artificial Insemination Done Numbers',
   'No.of animals treated',
   'Production of Milk in Thousand Tonnes',
   'Production of Eggs. in Lakhs Nos',
   'Meat Production in Tonnes'],
  ['1', '2', '377', '378', '379', '380', '381']],
 [['5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012'],
  ['',
   '',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012'],
  ['', '', 'Rabbits', 'Dogs', 'Others', 'Total Live Stock', 'Poultry'],
  ['1', '2', '365', '366', '367', '368', '369']],
 [['5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   '5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   '5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   '5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   '5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   '5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   '5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   '5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   '5.2 eterinary Hospitals on 31-03-2016 In Nos.'],
  ['Sl.No',
   'District',
   'Veterinary Institutions',
   'Veterinary Institutions',
   'Veterinary Institutions',
   'Veterinary Institutions',
   'Veterinary Institutions',
   'Veterinary Institutions',
   'Veterinary Institutions'],
  ['Sl.No',
   'District',
   'Veterinary Hospitals Kvs/rl',
   'Dispensaries',
   'Primary Veterinary Centres',
   'Mobile Dispensaries',
   'Artificial Insemination Centres',
   'Others',
   'Total'],
  ['1', '2', '370', '371', '372', '373', '374', '375', '376']],
 [['5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16',
   '5.4 Fisheries Year 2015-16'],
  ['',
   '',
   'Families involved in fisheries',
   'Families involved in fisheries',
   'No.of Beneficiaries under Mathsasrayascheme',
   'Fish lets In lakhs',
   'Fish markets No'],
  ['',
   '',
   'Full Time',
   'Part Time',
   'No.of Beneficiaries under Mathsasrayascheme',
   'Fish lets In lakhs',
   'Fish markets No'],
  ['1', '2', '389', '390', '391', '392', '393']],
 [['5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016',
   '5.4 Fisheries Year 2015-2016'],
  ['Sl.No.',
   'District',
   'Fish catch in tonnes',
   'Ice Plants',
   'Ice Plants',
   'Cold storages',
   'Cold storages',
   'Total tanks for fisheries',
   'Total tanks for fisheries'],
  ['Sl.No.',
   'District',
   'Fish catch in tonnes',
   'No.',
   'Capacity Tonnes day',
   'No.',
   'Capacity Tonnes',
   'Panchayat Raj',
   'Minor Irrigation'],
  ['1', '2', '382', '383', '384', '385', '386', '387', '388']]]

In [24]:
#transpose the inner list
transp_list = [[list(pair) for pair in zip(*sublist)] for sublist in output_list]
transp_list

[[['5.1 Livestock Census 2012 In Nos', '', '', '', '1'],
  ['5.1 Livestock Census 2012 In Nos', '', '', '', '2'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Cattle',
   'Indigenious',
   '351'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Cattle',
   'Exotic',
   '352'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Cattle',
   'Cross Breed',
   '353'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Cattle',
   'Total',
   '354'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Buffaloes',
   'Buffaloes',
   '355'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'heeps',
   'Indigenious',
   '356'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'heeps',
   'Exotic',
   '357'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'heeps',
   'Cross Breed',
   '358'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'heeps',
   'Total',
   '359'],
  ['5.1 Livestock Census 2012 In Nos', 'Livestock Census 2012', '', '', '']],
 [['5.1 Livestock Census 2012', 'Sl.No.', 'Sl.No.', 'Sl.No.', '1'],
  ['5.1 Livestock Census 2012', 'District', 'District', 'District', '2'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Goats',
   'Goats',
   '360'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Pigs',
   'Indigenious',
   '361'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Pigs',
   'Exotic',
   '362'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Pigs',
   'Cross Breed',
   '363'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Pigs',
   'Total',
   '364']],
 [['5.3 Artificial Insemination and Dairy Production Year 2015-16', '', '1'],
  ['5.3 Artificial Insemination and Dairy Production Year 2015-16', '', '2'],
  ['5.3 Artificial Insemination and Dairy Production Year 2015-16',
   'Artificial Insemination Done Numbers',
   '377'],
  ['5.3 Artificial Insemination and Dairy Production Year 2015-16',
   'No.of animals treated',
   '378'],
  ['5.3 Artificial Insemination and Dairy Production Year 2015-16',
   'Production of Milk in Thousand Tonnes',
   '379'],
  ['5.3 Artificial Insemination and Dairy Production Year 2015-16',
   'Production of Eggs. in Lakhs Nos',
   '380'],
  ['5.3 Artificial Insemination and Dairy Production Year 2015-16',
   'Meat Production in Tonnes',
   '381']],
 [['5.1 Livestock Census 2012', '', '', '1'],
  ['5.1 Livestock Census 2012', '', '', '2'],
  ['5.1 Livestock Census 2012', 'Livestock Census 2012', 'Rabbits', '365'],
  ['5.1 Livestock Census 2012', 'Livestock Census 2012', 'Dogs', '366'],
  ['5.1 Livestock Census 2012', 'Livestock Census 2012', 'Others', '367'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Total Live Stock',
   '368'],
  ['5.1 Livestock Census 2012', 'Livestock Census 2012', 'Poultry', '369']],
 [['5.2 eterinary Hospitals on 31-03-2016 In Nos.', 'Sl.No', 'Sl.No', '1'],
  ['5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   'District',
   'District',
   '2'],
  ['5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   'Veterinary Institutions',
   'Veterinary Hospitals Kvs/rl',
   '370'],
  ['5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   'Veterinary Institutions',
   'Dispensaries',
   '371'],
  ['5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   'Veterinary Institutions',
   'Primary Veterinary Centres',
   '372'],
  ['5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   'Veterinary Institutions',
   'Mobile Dispensaries',
   '373'],
  ['5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   'Veterinary Institutions',
   'Artificial Insemination Centres',
   '374'],
  ['5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   'Veterinary Institutions',
   'Others',
   '375'],
  ['5.2 eterinary Hospitals on 31-03-2016 In Nos.',
   'Veterinary Institutions',
   'Total',
   '376']],
 [['5.4 Fisheries Year 2015-16', '', '', '1'],
  ['5.4 Fisheries Year 2015-16', '', '', '2'],
  ['5.4 Fisheries Year 2015-16',
   'Families involved in fisheries',
   'Full Time',
   '389'],
  ['5.4 Fisheries Year 2015-16',
   'Families involved in fisheries',
   'Part Time',
   '390'],
  ['5.4 Fisheries Year 2015-16',
   'No.of Beneficiaries under Mathsasrayascheme',
   'No.of Beneficiaries under Mathsasrayascheme',
   '391'],
  ['5.4 Fisheries Year 2015-16',
   'Fish lets In lakhs',
   'Fish lets In lakhs',
   '392'],
  ['5.4 Fisheries Year 2015-16', 'Fish markets No', 'Fish markets No', '393']],
 [['5.4 Fisheries Year 2015-2016', 'Sl.No.', 'Sl.No.', '1'],
  ['5.4 Fisheries Year 2015-2016', 'District', 'District', '2'],
  ['5.4 Fisheries Year 2015-2016',
   'Fish catch in tonnes',
   'Fish catch in tonnes',
   '382'],
  ['5.4 Fisheries Year 2015-2016', 'Ice Plants', 'No.', '383'],
  ['5.4 Fisheries Year 2015-2016', 'Ice Plants', 'Capacity Tonnes day', '384'],
  ['5.4 Fisheries Year 2015-2016', 'Cold storages', 'No.', '385'],
  ['5.4 Fisheries Year 2015-2016', 'Cold storages', 'Capacity Tonnes', '386'],
  ['5.4 Fisheries Year 2015-2016',
   'Total tanks for fisheries',
   'Panchayat Raj',
   '387'],
  ['5.4 Fisheries Year 2015-2016',
   'Total tanks for fisheries',
   'Minor Irrigation',
   '388']]]

In [25]:
def find_table_details(input_string):
    # Regular expression to match numbers with dot similar to dd.dd, d.d, d.dd, or dd.d
    pattern = re.compile(r'\b(\d\.\d|\d{2}\.\d|\d\.\d{2}|\d{2}\.\d{2})\b')

    # Find all occurrences of the pattern in the input string
    matches = pattern.finditer(input_string)

    # Initialize variables to store the matches
    match_positions = []

    # Store the positions of the matches
    for match in matches:
        match_positions.append(match.start())

    # If there is at least one occurrence of the pattern
    if match_positions:
        table_id_index = match_positions[0]
        input_string = input_string[table_id_index:]  
        space_index = input_string.find(' ') 
        table_id = input_string[table_id_index:space_index].strip()
        table_name = input_string[space_index:].strip()
        return table_id, table_name    
    else:
        return None, None

In [26]:
def convert_to_number(string):
    try:
        number = int(string)
    except ValueError:
        try:
            number = float(string)
        except ValueError:
            raise ValueError("Input string is not a valid number")
    return number

In [27]:
chapter_id = 5
chapter_name = "Animal Husbandry"
#processing each column
def process_dictionary(input_data):
    df = pd.DataFrame(columns = ['Attr_id', 'Chapter_id', 'Chapter_name', 'Table_id', 'Table_name', 'Description'])
    for inner_list in input_data:
        table_id, table_name = find_table_details(inner_list[0][0])
        previd=0
        for data_list in inner_list:
            i=0
            attr_id=0
            description = ''
            prev = ''
            for data in reversed(data_list):
                if data == '1' or data == '2':
                    break
                i = i+1;
                if i == 1 and data!='' and (previd==0 or convert_to_number(data)!=previd):
                    attr_id = convert_to_number(data)
                    previd = convert_to_number(data)
                if i > 1 and i < len(data_list):
                    if description == '':
                        description = data
                        prev = data
                    else : 
                        if prev != data and data!='':
                            description = ','.join([description, data]) #description + ' ' + data
                            prev = data
            if attr_id != 0 and description != "" :
                row = {'Attr_id' : attr_id, 'Chapter_id' : chapter_id, 'Chapter_name' : chapter_name, 'Table_id' : table_id, 'Table_name' : table_name, 'Description' : remove_extra_spaces(description)}
                df.loc[len(df)] = row
    df = df.sort_values(by=['Attr_id'])
    df.to_csv(absolute_result_path, sep=';', index=False)
    df.to_csv(absolute_dictionary_path, sep=';', index=False)

In [28]:
process_dictionary(transp_list)