# Merging table header

In [22]:
import pandas as pd
import os

In [23]:
relative_path_data = "Data/"
relatice_path_result = "Data/Data_2019-20.csv"
absolute_path_data = os.path.join(os.getcwd(), relative_path_data)
absolute_path_result = os.path.join(os.getcwd(), relatice_path_result)

In [24]:
os.getcwd()

'/home/riya/Downloads/ADT/2019-20'

In [25]:
absolute_path_data

'/home/riya/Downloads/ADT/2019-20/Data/'

In [26]:
def concat_dataframe(df_list):
    df = pd.DataFrame()
    if len(df_list)>0:
        df = pd.concat([df, df_list[0].iloc[:,:2]], axis = 1)
        for item in df_list:
            df = pd.concat([df, item.iloc[:,2:]], axis = 1)
    return df

In [27]:
dfs = []

# Iterate over each file in the directory
for filename in os.listdir(absolute_path_data):
    if filename.endswith('.csv'):
        file_path = os.path.join(absolute_path_data, filename)
        # Read the CSV file into a DataFrame without header
        df = pd.read_csv(file_path, sep=';')
        dfs.append(df)

# Concatenate all DataFrames into a single DataFrame
merged_df = concat_dataframe(dfs)

# Display the merged DataFrame
merged_df

,1,2,790,791,792,793,794,795,796,797,...,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022
0,1,Bengaluru(U),20641,0,115941,136582,8453,72544,0,4758,...,259.62,1888.35,1064,942,88.53,271,494,370262,569526,99391
1,2,Bengaluru(R),36456,0,122364,158820,24381,123568,0,1302,...,907.54,2659.65,1274,1083,85.01,134,42,5168,34648,3243
2,3,Ramanagara,134447,0,125450,259897,30619,152391,0,547,...,1078.62,2543.22,2137,1873,87.65,180,11,3133,19060,2074
3,4,Chitradurga,241095,0,34794,275889,152852,939591,0,447,...,5508.97,9411.97,1645,1645,100.00,317,79,5460,46770,2352
4,5,Davanagere,150478,0,114722,265200,139222,176831,0,156,...,2631.91,5338.29,954,936,98.11,261,72,14241,325038,3701
5,6,Kolara,55416,0,173620,229036,45876,442903,2197,0,...,1503.48,3892.48,1951,1852,94.93,221,87,10058,303811,3846
6,7,Chikkaballapura,83709,0,162630,246339,47140,424558,0,8133,...,1958.94,4398.02,1919,1919,100.00,198,72,3654,49906,2047
7,8,Shivamogga,456368,0,112108,568476,149515,35633,0,1158,...,5171.44,9621.74,4739,4739,100.00,357,113,15467,244426,4946
8,9,Tumakuru,302707,0,224360,527067,181118,1060572,0,758,...,6770.52,11301.05,5125,4551,88.80,557,100,13714,276155,4071
9,10,Chikkamagaluru,257740,0,79836,337576,70870,91155,0,157,...,4535.29,8710.14,3671,1952,53.17,301,148,9578,250884,3146
10,11,Dakshina Kannada,113747,0,139968,253715,3700,242,0,23,...,5098.83,8768.85,7655,3063,40.01,471,170,51669,318451,14929
11,12,Udupi,155309,0,96758,252067,8846,61,0,9,...,4275.21,7348.37,3462,3227,93.21,325,91,22726,249926,9024
12,13,Hassan,337112,0,269348,606460,141264,159544,0,1141,...,4781.48,9659.04,3629,2596,71.53,414,87,10198,287347,3807
13,14,Kodagu,55595,0,32833,88428,14476,1158,0,243,...,1116.03,4243.81,569,416,73.11,213,76,10206,272560,4487
14,15,Mandya,153122,0,213618,366740,145516,339383,0,2391,...,4172.84,8573.28,2038,2038,100.00,353,62,5486,137500,2511
15,16,Mysuru,316327,0,233225,549552,45419,217001,0,1380,...,4185.13,8244.79,2002,1989,99.35,389,97,35437,265063,18921
16,17,Chamarajanagara,119629,0,142891,262520,20887,128314,0,169,...,2091.12,4249.51,913,877,96.06,204,41,2113,143526,1437
17,18,Belagavi,415839,0,176994,592833,829370,787386,0,1543,...,7265.66,12251.32,2738,2237,81.70,727,188,30749,200048,10258
18,19,Vijayapura,248310,0,4715,253025,156860,309240,0,38,...,5654.80,8444.96,1023,1133,110.75,400,102,8801,59641,3551
19,20,Bagalkot,236797,0,42618,279415,234802,733501,0,99,...,3587.14,5673.05,1072,749,69.87,329,58,6232,65625,3565
20,21,Dharwad,149877,0,43904,193781,79513,73690,0,292,...,3080.11,4170.67,388,373,96.13,209,67,37445,216380,14640
21,22,Gadag,118502,0,24153,142655,60989,258712,0,335,...,2550.88,3911.68,361,361,100.00,168,58,5682,40159,2257
22,23,Haveri,224776,0,59833,284609,98468,253708,0,1000,...,1962.02,3969.40,743,694,93.41,257,55,4776,61707,1965
23,24,Uttara Kannada,289788,0,47167,336955,87816,4549,0,234,...,8105.62,12515.44,7506,3558,47.40,483,150,28562,563476,10353
24,25,Ballari,370220,0,40732,410952,178929,915056,0,7405,...,4585.48,7392.65,1281,1281,100.00,447,131,13847,131985,5660
25,26,Bidar,219964,0,14555,234519,130781,88043,0,359,...,2519.90,4892.90,875,837,95.66,303,82,5859,47054,2318
26,27,Kalburgi,460488,0,12629,473117,91254,99843,0,218,...,4720.47,7498.35,1285,1285,100.00,421,97,11395,64383,3723
27,28,Yadgir,308133,0,2594,310727,76855,460889,0,2593,...,2284.00,3800.66,487,445,91.38,204,29,2258,46698,1587
28,29,Raichur,336753,0,22371,359124,136854,646356,0,1193,...,5092.18,7231.24,1315,680,51.71,286,81,5916,63290,3192
29,30,Koppal,234622,0,25786,260408,77860,547059,0,2,...,2115.37,3514.19,771,736,95.46,218,72,4452,47202,2069

In [28]:
merged_df.shape

(30, 1555)

In [29]:
final_df = merged_df.reindex(sorted(merged_df.columns, key=int), axis=1)

In [30]:
final_df

,1,2,3,4,5,6,7,8,9,10,...,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562
0,1,Bengaluru(U),5,27,93,227,562,26,588,1,...,4,71766,3600,3209,0,6809,1911,1482,0,3393
1,2,Bengaluru(R),4,17,105,191,957,94,1051,0,...,0,6840,277,186,0,463,477,245,0,722
2,3,Ramanagara,4,18,127,242,820,52,872,0,...,1,8899,192,142,0,334,579,344,0,923
3,4,Chitradurga,6,22,189,311,948,115,1063,0,...,0,12650,524,367,0,891,1278,932,0,2210
4,5,Davanagere,6,20,196,231,721,122,843,1,...,0,14379,2815,1721,0,4536,696,492,0,1188
5,6,Kolara,6,27,156,260,1608,189,1797,0,...,1,10122,1547,1039,0,2586,707,238,0,945
6,7,Chikkaballapura,6,26,157,247,1324,189,1513,0,...,0,8450,872,472,0,1344,519,327,0,846
7,8,Shivamogga,7,37,271,361,1444,86,1530,1,...,1,14763,484,361,0,845,550,485,0,1035
8,9,Tumakuru,10,53,330,560,2582,133,2715,1,...,1,22415,621,385,0,1006,1926,1448,1,3374
9,10,Chikkamagaluru,8,34,226,237,1022,95,1117,0,...,0,8534,263,191,0,454,567,415,0,982
10,11,Dakshina Kannada,7,17,230,286,331,0,331,1,...,3,20774,235,277,0,512,470,293,0,763
11,12,Udupi,7,9,158,187,233,0,233,0,...,0,11568,261,287,0,548,352,235,0,587
12,13,Hassan,8,38,267,406,2418,156,2574,0,...,0,14792,1420,936,1,2356,1950,934,0,2884
13,14,Kodagu,3,16,104,109,291,5,296,0,...,0,4053,123,105,0,228,298,107,0,405
14,15,Mandya,7,45,233,415,1368,109,1477,0,...,2,14936,223,152,1,375,1019,499,0,1518
15,16,Mysuru,8,33,266,429,1199,137,1336,1,...,1,27274,755,609,0,1364,2598,1708,0,4306
16,17,Chamarajanagara,5,16,130,222,428,81,509,0,...,0,8572,546,404,0,950,873,486,0,1359
17,18,Belagavi,14,38,506,563,1263,12,1275,1,...,1,35840,1329,828,0,2157,737,400,0,1137
18,19,Vijayapura,12,20,212,206,679,13,692,1,...,0,16312,2899,1872,0,4771,454,326,0,780
19,20,Bagalkot,9,18,198,244,613,11,624,0,...,1,14564,1740,1154,0,2894,262,274,0,536
20,21,Dharwad,8,14,144,199,361,18,379,1,...,2,18009,436,372,0,808,242,263,0,505
21,22,Gadag,7,11,122,194,322,15,337,0,...,0,8683,480,330,0,810,309,265,0,574
22,23,Haveri,8,19,224,256,696,7,703,0,...,0,10691,322,214,0,536,197,225,0,422
23,24,Uttara Kannada,12,35,231,239,1243,46,1289,0,...,1,10526,290,295,0,585,175,178,0,353
24,25,Ballari,11,31,237,341,601,31,632,1,...,2,18858,3068,1981,0,5049,2305,1700,0,4005
25,26,Bidar,8,30,185,302,595,25,620,0,...,0,11088,4517,3112,0,7629,376,112,0,488
26,27,Kalburgi,11,32,264,351,871,47,918,1,...,0,17015,4377,2930,1,7307,579,269,0,848
27,28,Yadgir,6,16,123,169,487,26,513,0,...,0,6894,1494,920,0,2414,506,169,0,675
28,29,Raichur,7,37,179,280,815,69,884,0,...,2,11333,3765,2366,1,6131,545,186,0,731
29,30,Koppal,7,20,153,157,595,34,629,0,...,0,8833,1234,738,0,1972,419,253,0,672

In [31]:
final_df.to_csv(absolute_path_result, sep=';', index=False)

In [32]:
for i in range(3,1562):
    if str(i) not in final_df.columns.tolist():
        print(i)

156
157
158
159
160
161
162

These columns are not present as they have "Age group" data