# Extracting table header as list

In [2]:
import collections
collections.Callable = collections.abc.Callable

In [3]:
from bs4 import BeautifulSoup, NavigableString
from html_table_extractor.extractor import Extractor
import pandas as pd
import os
import re

In [4]:
path = "/home/riya/Downloads/ADT/Output_html_Chapter5/kaggle/working/output/"

In [5]:
os.chdir(path)

In [6]:
os.listdir()

['output_page_1.html',
 'output_page_2.html',
 'output_page_5.html',
 'output_page_3.html',
 'output_page_4.html',
 'output_page_7.html',
 'output_page_6.html']

In [7]:
output_list = []

In [8]:
output_list

[]

In [9]:
allowed_two_letter_words = {'sl','sc', 'st', 'cc', 'tp', 'tb', 'ts', 'tg', 'km', 'gm', 'an', 'at', 'by', 'do', 'go', 'if', 'in', 'is', 'it', 'me', 'my', 'no', 'of', 'on', 'or', 'so', 'to', 'up', 'us'}

def replace_td_content(tag):
    if isinstance(tag, NavigableString):
        return  # Skip strings, as they don't have 'contents'

    if tag.name == 'td':
        # Extract only meaningful English words and numbers
        valid_characters = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-.%")
        filtered_content = ''.join(char if char in valid_characters else ' ' for char in tag.get_text())
        
        # Remove extra spaces and words with less than 3 characters
        cleaned_content = ' '.join(word for word in filtered_content.split() if len(word) >= 3 or word.isdigit() or word.lower() in allowed_two_letter_words or word=='%')
        
        # Set the cleaned content as the tag's string
        tag.string = cleaned_content
    elif tag.contents:
        for child in tag.contents:
            replace_td_content(child)

In [10]:
def process_table_cells(target_table):
    if not target_table:
        print("Table not found in the HTML content.")
        return

    flag1 = 0
    flag2 = 0

    # Loop through each row in the table
    for row in target_table.find_all('tr'):
        # Loop through each cell in the row
        if(flag1 == 1 and flag2 == 1):
            row.decompose()
        else : 
            for cell in row.find_all(['td', 'th']):
                # Process the cell content (you can modify this part based on your requirements)
                cell_content = cell.get_text(strip=True)
                if(cell_content == '1'):
                    flag1 = 1
                if(cell_content == '2'):
                    flag2 = 1

In [11]:
# iterate through all file 
for file in os.listdir(): 
    # Check whether file is in text format or not 
    if file.endswith(".html"): 
        file_path = f"{path}{file}"
  
        with open(file_path) as fp:
            soup = BeautifulSoup(fp, "html.parser")
            
            for tag in soup.find_all(attrs={'style': True}):
                tag.attrs.pop('style')
            
            table_tag = soup.find('table')
            
            replace_td_content(table_tag)

            process_table_cells(table_tag)
            
            extractor1 = Extractor(table_tag)
            extractor1.parse()
            output_list.append(extractor1.return_list())

In [12]:
output_list

[[['Animal Husbandry5.1 2012 Livestock Census 2012 In Nos',
   'Animal Husbandry5.1 2012 Livestock Census 2012 In Nos',
   'Animal Husbandry5.1 2012 Livestock Census 2012 In Nos',
   'Animal Husbandry5.1 2012 Livestock Census 2012 In Nos',
   'Animal Husbandry5.1 2012 Livestock Census 2012 In Nos',
   'Animal Husbandry5.1 2012 Livestock Census 2012 In Nos',
   'Animal Husbandry5.1 2012 Livestock Census 2012 In Nos',
   'Animal Husbandry5.1 2012 Livestock Census 2012 In Nos',
   'Animal Husbandry5.1 2012 Livestock Census 2012 In Nos',
   'Animal Husbandry5.1 2012 Livestock Census 2012 In Nos',
   'Animal Husbandry5.1 2012 Livestock Census 2012 In Nos'],
  ['',
   'ffl',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012'],
  ['',
   'ffl',
   'Cattle',
   'Cattle',
   'Cattle',
   'Cattle',
   'Buffaloes',
   'Sheeps',
   'Sheeps',
   'Sheeps',
   'Sheeps'],
  ['',
   'ffl',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total',
   'Buffaloes',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total'],
  ['1', '2', '351', '352', '353', '354', '355', '356', '357', '358', '359']],
 [['5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012'],
  ['Sl.No.',
   'District',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012',
   'LivestockCensus 2012'],
  ['Sl.No.', 'District', 'Goats', 'Pigs', 'Pigs', 'Pigs', 'Pigs'],
  ['Sl.No.',
   'District',
   'Goats',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total'],
  ['1', '2', '360', '361', '362', '363', '364']],
 [['5.3 ArtificialInsemination and Dairy Production Year 2016-17',
   '5.3 ArtificialInsemination and Dairy Production Year 2016-17',
   '5.3 ArtificialInsemination and Dairy Production Year 2016-17',
   '5.3 ArtificialInsemination and Dairy Production Year 2016-17',
   '5.3 ArtificialInsemination and Dairy Production Year 2016-17',
   '5.3 ArtificialInsemination and Dairy Production Year 2016-17',
   '5.3 ArtificialInsemination and Dairy Production Year 2016-17'],
  ['',
   'fUfl',
   'Artificial InseminationDone Numbers',
   'No.of animalstreated',
   'Production of Milk in Thousand Tonnes',
   'Productionof Eggs. in LakhsNos',
   'Meat Productio inTonnes'],
  ['1', '2', '377', '378', '379', '380', '381']],
 [['5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012',
   '5.1 2012 Livestock Census 2012'],
  ['',
   'ffl',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012'],
  ['', 'ffl', 'Rabbits', 'Dogs', 'Others', 'Total LiveStock', 'Poultry'],
  ['1', '2', '365', '366', '367', '368', '369']],
 [['5.2 terinary Hospitals on 31.3.2017 In Nos.',
   '5.2 terinary Hospitals on 31.3.2017 In Nos.',
   '5.2 terinary Hospitals on 31.3.2017 In Nos.',
   '5.2 terinary Hospitals on 31.3.2017 In Nos.',
   '5.2 terinary Hospitals on 31.3.2017 In Nos.',
   '5.2 terinary Hospitals on 31.3.2017 In Nos.',
   '5.2 terinary Hospitals on 31.3.2017 In Nos.',
   '5.2 terinary Hospitals on 31.3.2017 In Nos.',
   '5.2 terinary Hospitals on 31.3.2017 In Nos.'],
  ['Sl.No',
   'District',
   'erinary Institutions',
   'erinary Institutions',
   'erinary Institutions',
   'erinary Institutions',
   'erinary Institutions',
   'erinary Institutions',
   'erinary Institutions'],
  ['Sl.No',
   'District',
   'Veterinary Hospitals KVS',
   'Dispensaries',
   'Primary Veterinary Centres',
   'fiAi Mobile Dispensaries',
   'Artificial InseminationCentres',
   'Others',
   'Total'],
  ['1', '2', '370', '371', '372', '373', '374', '375', '376']],
 [['5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17'],
  ['',
   'ffl',
   'Families involved in fisheries',
   'Families involved in fisheries',
   'No.of Beneficiaries under Mathsasrayascheme',
   'fiP Fish lets In lakhs',
   'Fish markets No'],
  ['',
   'ffl',
   'Full Time',
   'Part Time',
   'No.of Beneficiaries under Mathsasrayascheme',
   'fiP Fish lets In lakhs',
   'Fish markets No'],
  ['1', '2', '389', '390', '391', '392', '393']],
 [['5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17'],
  ['Sl.No.',
   'District',
   'Fishcatch in tonnes',
   'Ice Plants',
   'Ice Plants',
   'Cold storages',
   'Cold storages',
   'Total tanks for fisheries',
   'Total tanks for fisheries'],
  ['Sl.No.',
   'District',
   'Fishcatch in tonnes',
   'No.',
   'Capacity Tonnes day',
   'No.',
   'Capacity Tonnes',
   'A.g Panchayat Raj',
   'Minor Irrigation'],
  ['1', '2', '382', '383', '384', '385', '386', '387', '388']]]

In [126]:
#list_to_remove = [[['4.18. Sericulture Year 2016-17 in Nos.',
   '4.18. Sericulture Year 2016-17 in Nos.',
   '4.18. Sericulture Year 2016-17 in Nos.',
   '4.18. Sericulture Year 2016-17 in Nos.',
   '4.18. Sericulture Year 2016-17 in Nos.',
   '4.18. Sericulture Year 2016-17 in Nos.',
   '4.18. Sericulture Year 2016-17 in Nos.',
   '4.18. Sericulture Year 2016-17 in Nos.',
   '4.18. Sericulture Year 2016-17 in Nos.',
   '4.18. Sericulture Year 2016-17 in Nos.',
   '4.18. Sericulture Year 2016-17 in Nos.',
   '4.18. Sericulture Year 2016-17 in Nos.'],
  ['Sl.No.',
   'District',
   '',
   '',
   '',
   '',
   'fiv',
   'fiv',
   'fiv',
   'fiv',
   'PjU 2013g',
   'PjU 2013g'],
  ['Sl.No.',
   'District',
   '',
   'fiT',
   'SOthers',
   'Total',
   '',
   'fST',
   'Others',
   'Total',
   'PjU 2013g',
   'PjU 2013g'],
  ['Sl.No.',
   'District',
   '',
   'fiT',
   'SOthers',
   'Total',
   '',
   'fST',
   'Others',
   'Total',
   'SCP',
   'TSP'],
  ['1',
   '2',
   '341',
   '342',
   '343',
   '344',
   '345',
   '346',
   '347',
   '348',
   '349',
   '350']]]

In [127]:
#for list_set in output_list:
    for item in list_to_remove: 
        if(list_set == item):
            output_list.remove(list_set)

In [128]:
#list_to_add = [[['4.18 Sericulture Year 2016-17 in Nos.',
   '4.18 Sericulture Year 2016-17 in Nos.',
   '4.18 Sericulture Year 2016-17 in Nos.',
   '4.18 Sericulture Year 2016-17 in Nos.',
   '4.18 Sericulture Year 2016-17 in Nos.',
   '4.18 Sericulture Year 2016-17 in Nos.',
   '4.18 Sericulture Year 2016-17 in Nos.',
   '4.18 Sericulture Year 2016-17 in Nos.',
   '4.18 Sericulture Year 2016-17 in Nos.',
   '4.18 Sericulture Year 2016-17 in Nos.',
   '4.18 Sericulture Year 2016-17 in Nos.',
   '4.18 Sericulture Year 2016-17 in Nos.'],
  ['Sl.No.',
   'District',
   'Set1',
   'Set1',
   'Set1',
   'Set1',
   'Set2',
   'Set2',
   'Set2',
   'Set2',
   '',
   ''],
  ['Sl.No.',
   'District',
   'SC',
   'ST',
   'Others',
   'Total',
   'SC',
   'ST',
   'Others',
   'Total',
   '',
   ''],
  ['Sl.No.',
   'District',
   'SC',
   'ST',
   'Others',
   'Total',
   'SC',
   'ST',
   'Others',
   'Total',
   'SCP',
   'TSP'],
  ['1',
   '2',
   '341',
   '342',
   '343',
   '344',
   '345',
   '346',
   '347',
   '348',
   '349',
   '350']]]

for item in list_to_add:
    output_list.append(item)

In [129]:
#output_list

[[['4.12 Yield of Important Crops Year 2014-15 Provis',
   '4.12 Yield of Important Crops Year 2014-15 Provis',
   '4.12 Yield of Important Crops Year 2014-15 Provis',
   '4.12 Yield of Important Crops Year 2014-15 Provis',
   '4.12 Yield of Important Crops Year 2014-15 Provis',
   '4.12 Yield of Important Crops Year 2014-15 Provis',
   '4.12 Yield of Important Crops Year 2014-15 Provis',
   '4.12 Yield of Important Crops Year 2014-15 Provis',
   '4.12 Yield of Important Crops Year 2014-15 Provis',
   '4.12 Yield of Important Crops Year 2014-15 Provis',
   '4.12 Yield of Important Crops Year 2014-15 Provis',
   '4.12 Yield of Important Crops Year 2014-15 Provis'],
  ['Sl.NO',
   'Districts',
   'ige Of Pulses K.G Hect',
   'ige Of Pulses K.G Hect',
   'ige Of Pulses K.G Hect',
   'ige Of Pulses K.G Hect',
   'ige Of Pulses K.G Hect',
   'ige Of Pulses K.G Hect',
   'ige Of Pulses K.G Hect',
   'ige Of Pulses K.G Hect',
   'ige Of Pulses K.G Hect',
   'ige Of Pulses K.G Hect'],
  ['Sl.NO',
   'Districts',
   'Tur',
   'Horse Gram',
   'Black Gram',
   'Green Gram',
   'Avare',
   'Cfi Cowpea',
   'Bengal Gram',
   'Other Pulses',
   'Total Pulses',
   'TotalFood Grains'],
  ['1',
   '2',
   '285',
   '286',
   '287',
   '288',
   '289',
   '290',
   '291',
   '292',
   '293',
   '294']],
 [['4.10 Production of Important Horticulture Crops Fruits Crops M.Tonnes Year 2015-16',
   '4.10 Production of Important Horticulture Crops Fruits Crops M.Tonnes Year 2015-16',
   '4.10 Production of Important Horticulture Crops Fruits Crops M.Tonnes Year 2015-16',
   '4.10 Production of Important Horticulture Crops Fruits Crops M.Tonnes Year 2015-16',
   '4.10 Production of Important Horticulture Crops Fruits Crops M.Tonnes Year 2015-16',
   '4.10 Production of Important Horticulture Crops Fruits Crops M.Tonnes Year 2015-16',
   '4.10 Production of Important Horticulture Crops Fruits Crops M.Tonnes Year 2015-16',
   '4.10 Production of Important Horticulture Crops Fruits Crops M.Tonnes Year 2015-16',
   '4.10 Production of Important Horticulture Crops Fruits Crops M.Tonnes Year 2015-16',
   '4.10 Production of Important Horticulture Crops Fruits Crops M.Tonnes Year 2015-16',
   '4.10 Production of Important Horticulture Crops Fruits Crops M.Tonnes Year 2015-16'],
  ['',
   'ffl',
   'Banana',
   'Mango',
   'Lemon',
   'PineApple',
   'Guava',
   'Grapes',
   'Sapota',
   'Poma-granate',
   'Papaya'],
  ['1', '2', '259', '260', '261', '262', '263', '264', '265', '266', '267']],
 [['4.6 rod uction of Important CropsYear 2014-15 Provision in Tonnes',
   '4.6 rod uction of Important CropsYear 2014-15 Provision in Tonnes',
   '4.6 rod uction of Important CropsYear 2014-15 Provision in Tonnes',
   '4.6 rod uction of Important CropsYear 2014-15 Provision in Tonnes',
   '4.6 rod uction of Important CropsYear 2014-15 Provision in Tonnes',
   '4.6 rod uction of Important CropsYear 2014-15 Provision in Tonnes',
   '4.6 rod uction of Important CropsYear 2014-15 Provision in Tonnes',
   '4.6 rod uction of Important CropsYear 2014-15 Provision in Tonnes',
   '4.6 rod uction of Important CropsYear 2014-15 Provision in Tonnes',
   '4.6 rod uction of Important CropsYear 2014-15 Provision in Tonnes'],
  ['Sl.No',
   'Districts',
   'oduction of Cereals',
   'oduction of Cereals',
   'oduction of Cereals',
   'oduction of Cereals',
   'oduction of Cereals',
   'oduction of Cereals',
   'oduction of Cereals',
   'oduction of Cereals'],
  ['Sl.No',
   'Districts',
   'Rice',
   'Jowar',
   'Bajra',
   'Maize',
   'Ragi',
   'Wheat',
   'tzs Total Small Minor Millets',
   'Total Cereals Minor Millets'],
  ['1', '2', '223', '224', '225', '226', '227', '228', '229', '230']],
 [['4.11 Production of Important Vegetable Crops in.Tons Year 2015-16',
   '4.11 Production of Important Vegetable Crops in.Tons Year 2015-16',
   '4.11 Production of Important Vegetable Crops in.Tons Year 2015-16',
   '4.11 Production of Important Vegetable Crops in.Tons Year 2015-16',
   '4.11 Production of Important Vegetable Crops in.Tons Year 2015-16',
   '4.11 Production of Important Vegetable Crops in.Tons Year 2015-16',
   '4.11 Production of Important Vegetable Crops in.Tons Year 2015-16',
   '4.11 Production of Important Vegetable Crops in.Tons Year 2015-16',
   '4.11 Production of Important Vegetable Crops in.Tons Year 2015-16',
   '4.11 Production of Important Vegetable Crops in.Tons Year 2015-16',
   '4.11 Production of Important Vegetable Crops in.Tons Year 2015-16'],
  ['Sl.No',
   'Districts',
   'Dfi Potato',
   'Tomato',
   'Brinjal',
   'Beans',
   'Cluster Beans',
   'Onion',
   'Green Chillies',
   'Total Leafy Vegetables',
   'Total Gourd Variety Vegetables'],
  ['1', '2', '268', '269', '270', '271', '272', '273', '274', '275', '276']],
 [['Agriculture Horticulture and Sericulture4.1 Pnd Utilisation in Hectares',
   'Agriculture Horticulture and Sericulture4.1 Pnd Utilisation in Hectares',
   'Agriculture Horticulture and Sericulture4.1 Pnd Utilisation in Hectares',
   'Agriculture Horticulture and Sericulture4.1 Pnd Utilisation in Hectares',
   'Agriculture Horticulture and Sericulture4.1 Pnd Utilisation in Hectares',
   'Agriculture Horticulture and Sericulture4.1 Pnd Utilisation in Hectares',
   'Agriculture Horticulture and Sericulture4.1 Pnd Utilisation in Hectares',
   'Agriculture Horticulture and Sericulture4.1 Pnd Utilisation in Hectares',
   'Agriculture Horticulture and Sericulture4.1 Pnd Utilisation in Hectares',
   'Agriculture Horticulture and Sericulture4.1 Pnd Utilisation in Hectares',
   'Agriculture Horticulture and Sericulture4.1 Pnd Utilisation in Hectares'],
  ['Sl.No',
   'District',
   'and Utilisation 2015-16',
   'and Utilisation 2015-16',
   'and Utilisation 2015-16',
   'and Utilisation 2015-16',
   'and Utilisation 2015-16',
   'and Utilisation 2015-16',
   'and Utilisation 2015-16',
   'and Utilisation 2015-16',
   'and Utilisation 2015-16'],
  ['Sl.No',
   'District',
   'Geo- graphical Area',
   'Forest',
   'Land notavailable for cultivation',
   'Land notavailable for cultivation',
   'Land notavailable for cultivation',
   'Other Uncultivated Land',
   'Other Uncultivated Land',
   'Other Uncultivated Land',
   'Other Uncultivated Land'],
  ['Sl.No',
   'District',
   'Geo- graphical Area',
   'Forest',
   'Land put to Non- Agricultural uses',
   'Adg Barren cultivable land',
   'Total',
   'Adg Cultivable- waste',
   'Permanent Pasture',
   'Trees and Groves',
   'Total'],
  ['1', '2', '156', '157', '158', '159', '160', '161', '162', '163', '164']],
 [['4.1 Utilisation in Hectares',
   '4.1 Utilisation in Hectares',
   '4.1 Utilisation in Hectares',
   '4.1 Utilisation in Hectares',
   '4.1 Utilisation in Hectares',
   '4.1 Utilisation in Hectares',
   '4.1 Utilisation in Hectares',
   '4.1 Utilisation in Hectares'],
  ['',
   'ffl',
   'and Utilisation2015-16 in Hectares',
   'and Utilisation2015-16 in Hectares',
   'and Utilisation2015-16 in Hectares',
   'and Utilisation2015-16 in Hectares',
   'and Utilisation2015-16 in Hectares',
   'and Utilisation2015-16 in Hectares'],
  ['',
   'ffl',
   'Fallow Land',
   'Fallow Land',
   'Fallow Land',
   'Area Sown',
   'Area Sown',
   'Area Sown'],
  ['', 'ffl', 'Current', 'Other', 'Total', 'Net', 'More than once', 'Total'],
  ['1', '2', '165', '166', '167', '168', '169', '170']],
 [['4.3 At under principal crops Year 2015-16',
   '4.3 At under principal crops Year 2015-16',
   '4.3 At under principal crops Year 2015-16',
   '4.3 At under principal crops Year 2015-16',
   '4.3 At under principal crops Year 2015-16',
   '4.3 At under principal crops Year 2015-16',
   '4.3 At under principal crops Year 2015-16',
   '4.3 At under principal crops Year 2015-16',
   '4.3 At under principal crops Year 2015-16',
   '4.3 At under principal crops Year 2015-16'],
  ['Sl.No.',
   'Districts',
   'Area under principal crops InHect.',
   'Area under principal crops InHect.',
   'Area under principal crops InHect.',
   'Area under principal crops InHect.',
   'Area under principal crops InHect.',
   'Area under principal crops InHect.',
   'Area under principal crops InHect.',
   'Area under principal crops InHect.'],
  ['Sl.No.',
   'Districts',
   'Area under Cereals Hect.',
   'Area under Cereals Hect.',
   'Area under Cereals Hect.',
   'Area under Cereals Hect.',
   'Area under Cereals Hect.',
   'Area under Cereals Hect.',
   'Area under Cereals Hect.',
   'Area under Cereals Hect.'],
  ['Sl.No.',
   'Districts',
   'Paddy',
   'Jowar',
   'Bajra',
   'Maize',
   'Ragi',
   'Wheat',
   'Other Cereals Minor Millets',
   'Total Cereals Minor millets'],
  ['1', '2', '190', '191', '192', '193', '194', '195', '196', '197']],
 [['4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes',
   '4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes',
   '4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes',
   '4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes',
   '4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes',
   '4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes',
   '4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes',
   '4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes',
   '4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes',
   '4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes',
   '4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes',
   '4.6 zPr duction of portant Cro psYear Year 2014-15 Provision in Tonnes'],
  ['',
   'ffl',
   'uction of Pulses In Tonnes',
   'uction of Pulses In Tonnes',
   'uction of Pulses In Tonnes',
   'uction of Pulses In Tonnes',
   'uction of Pulses In Tonnes',
   'uction of Pulses In Tonnes',
   'uction of Pulses In Tonnes',
   'uction of Pulses In Tonnes',
   'uction of Pulses In Tonnes',
   'uction of Pulses In Tonnes'],
  ['',
   'ffl',
   'Tur',
   'Horse Gram',
   'Black Gram',
   'Green Gram',
   'Avare',
   'Cfi Cowpea',
   'Bengal Gram',
   'Other Pulses',
   'Total Pulses',
   'Total Food Grains'],
  ['1',
   '2',
   '231',
   '232',
   '233',
   '234',
   '235',
   '236',
   '237',
   '238',
   '239',
   '240']],
 [['4.4 ret under Important Oil Seeds Year 2015-16',
   '4.4 ret under Important Oil Seeds Year 2015-16',
   '4.4 ret under Important Oil Seeds Year 2015-16',
   '4.4 ret under Important Oil Seeds Year 2015-16',
   '4.4 ret under Important Oil Seeds Year 2015-16',
   '4.4 ret under Important Oil Seeds Year 2015-16',
   '4.4 ret under Important Oil Seeds Year 2015-16',
   '4.4 ret under Important Oil Seeds Year 2015-16',
   '4.4 ret under Important Oil Seeds Year 2015-16',
   '4.4 ret under Important Oil Seeds Year 2015-16',
   '4.4 ret under Important Oil Seeds Year 2015-16',
   '4.4 ret under Important Oil Seeds Year 2015-16'],
  ['',
   'ffl',
   'Area under principal crops',
   'Area under principal crops',
   'Area under principal crops',
   'Area under principal crops',
   'Area under principal crops',
   'Area under principal crops',
   'Area under principal crops',
   'Area under principal crops',
   'Area under principal crops',
   'Area under principal crops'],
  ['',
   'ffl',
   'Seeds Hect',
   'Seeds Hect',
   'Seeds Hect',
   'Seeds Hect',
   'Seeds Hect',
   'Seeds Hect',
   'Seeds Hect',
   'Seeds Hect',
   'Seeds Hect',
   'Seeds Hect'],
  ['',
   'ffl',
   'GroundNut',
   'Sun Flower',
   'Safflower',
   'Castor',
   'Sesamum',
   'Niger seed',
   'Soyabean',
   'Linseed',
   'other oil Seeds',
   'Total oil Seeds'],
  ['1',
   '2',
   '210',
   '211',
   '212',
   '213',
   '214',
   '215',
   '216',
   '217',
   '218',
   '219']],
 [['4.15 jYield of Plantation crops in Kgs Hect Year 2014-15 Provision',
   '4.15 jYield of Plantation crops in Kgs Hect Year 2014-15 Provision',
   '4.15 jYield of Plantation crops in Kgs Hect Year 2014-15 Provision',
   '4.15 jYield of Plantation crops in Kgs Hect Year 2014-15 Provision',
   '4.15 jYield of Plantation crops in Kgs Hect Year 2014-15 Provision',
   '4.15 jYield of Plantation crops in Kgs Hect Year 2014-15 Provision',
   '4.15 jYield of Plantation crops in Kgs Hect Year 2014-15 Provision'],
  ['Sl.NO',
   'Districts',
   'CrP Arecanut Processed',
   'KfiQ Cardamom',
   'Pepper',
   'Cashewnut Processed',
   'Cocoa M.Tonnes Hect'],
  ['1', '2', '307', '308', '309', '310', '311']],
 [['4.13 jield of Important Oil Seeds 2014-15 Provision',
   '4.13 jield of Important Oil Seeds 2014-15 Provision',
   '4.13 jield of Important Oil Seeds 2014-15 Provision',
   '4.13 jield of Important Oil Seeds 2014-15 Provision',
   '4.13 jield of Important Oil Seeds 2014-15 Provision',
   '4.13 jield of Important Oil Seeds 2014-15 Provision',
   '4.13 jield of Important Oil Seeds 2014-15 Provision',
   '4.13 jield of Important Oil Seeds 2014-15 Provision',
   '4.13 jield of Important Oil Seeds 2014-15 Provision',
   '4.13 jield of Important Oil Seeds 2014-15 Provision',
   '4.13 jield of Important Oil Seeds 2014-15 Provision'],
  ['',
   'ffl',
   'ield Of Oil Seeds K.G Hect',
   'ield Of Oil Seeds K.G Hect',
   'ield Of Oil Seeds K.G Hect',
   'ield Of Oil Seeds K.G Hect',
   'ield Of Oil Seeds K.G Hect',
   'ield Of Oil Seeds K.G Hect',
   'ield Of Oil Seeds K.G Hect',
   'ield Of Oil Seeds K.G Hect',
   'ield Of Oil Seeds K.G Hect'],
  ['',
   'ffl',
   'Ground Nut',
   'Sun Flower',
   'Safflower',
   'Castor',
   'Linseed',
   'Soyabean',
   'Sesamum',
   'Nigerseed',
   'Total oil Seeds'],
  ['1', '2', '295', '296', '297', '298', '299', '300', '301', '302', '303']],
 [['4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources'],
  ['Sl.No.',
   'Districts',
   'jAi 2015-16 Net area irrigated Hectares',
   'jAi 2015-16 Net area irrigated Hectares',
   'jAi 2015-16 Net area irrigated Hectares',
   'jAi 2015-16 Net area irrigated Hectares',
   'jAi 2015-16 Net area irrigated Hectares',
   'jAi 2015-16 Net area irrigated Hectares',
   'jAi 2015-16 Net area irrigated Hectares',
   'jAi 2015-16 Net area irrigated Hectares',
   'jAi 2015-16 Net area irrigated Hectares'],
  ['Sl.No.',
   'Districts',
   'Canals',
   'Canals',
   'Canals',
   'Tanks',
   'Tanks',
   'Tanks',
   'Wells',
   'Wells',
   'Wells'],
  ['Sl.No.',
   'Districts',
   'Length inKMs',
   'jAi Gross Irrigated Area',
   'Net Area Irrigated',
   'Nos',
   'jAi Gross Irrigated Area',
   'Net Area Irrigated',
   'Nos',
   'jAi Gross Irrigated Area',
   'NetArea Irrigated'],
  ['1', '2', '171', '172', '173', '174', '175', '176', '177', '178', '179']],
 [['4.8 roduction of commercialcrops in Tonnes Year 2014-15 Provision',
   '4.8 roduction of commercialcrops in Tonnes Year 2014-15 Provision',
   '4.8 roduction of commercialcrops in Tonnes Year 2014-15 Provision',
   '4.8 roduction of commercialcrops in Tonnes Year 2014-15 Provision',
   '4.8 roduction of commercialcrops in Tonnes Year 2014-15 Provision'],
  ['', 'ffl', 'Cotton', 'Sugarcane', 'Tobacco'],
  ['1', '2', '250', '251', '252']],
 [['4.14 jYield of Commercial crops in Kgs Hectare Year 2014-15 Provision',
   '4.14 jYield of Commercial crops in Kgs Hectare Year 2014-15 Provision',
   '4.14 jYield of Commercial crops in Kgs Hectare Year 2014-15 Provision',
   '4.14 jYield of Commercial crops in Kgs Hectare Year 2014-15 Provision',
   '4.14 jYield of Commercial crops in Kgs Hectare Year 2014-15 Provision'],
  ['Sl.NO',
   'Districts',
   'Cotton in Bales',
   'Sugar Cane In Tonnes perHectare',
   'Tobacco'],
  ['1', '2', '304', '305', '306']],
 [['4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources',
   '4.2 fiU jAi Gross and Net area Irrigated under Different Sources'],
  ['',
   'ffl',
   'jAi area Irrigated under Different Sources 2015-16',
   'jAi area Irrigated under Different Sources 2015-16',
   'jAi area Irrigated under Different Sources 2015-16',
   'jAi area Irrigated under Different Sources 2015-16',
   'jAi area Irrigated under Different Sources 2015-16',
   'jAi area Irrigated under Different Sources 2015-16',
   'jAi area Irrigated under Different Sources 2015-16',
   'jAi area Irrigated under Different Sources 2015-16',
   'jAi area Irrigated under Different Sources 2015-16',
   'jAi area Irrigated under Different Sources 2015-16'],
  ['',
   'ffl',
   'Wells',
   'Wells',
   'Wells',
   'LiftIrrigation',
   'LiftIrrigation',
   'LiftIrrigation',
   'fiU Other Sources',
   'fiU Other Sources',
   'Total',
   'Total'],
  ['',
   'ffl',
   'Nos',
   'Gross Irrigated Area',
   'NetArea Irrigated',
   'Nos',
   'jAi GrossIrrigated Area',
   'Net Area Irrigated',
   'jAi Gross Irrigated Area',
   'NetArea Irrigated',
   'jAi Gross Irrigated Area',
   'NetArea Irrigated'],
  ['1',
   '2',
   '180',
   '181',
   '182',
   '183',
   '184',
   '185',
   '186',
   '187',
   '188',
   '189']],
 [['4.16 Distributionof chemical fertilizers InTonnes Year 2016-17',
   '4.16 Distributionof chemical fertilizers InTonnes Year 2016-17',
   '4.16 Distributionof chemical fertilizers InTonnes Year 2016-17',
   '4.16 Distributionof chemical fertilizers InTonnes Year 2016-17',
   '4.16 Distributionof chemical fertilizers InTonnes Year 2016-17',
   '4.16 Distributionof chemical fertilizers InTonnes Year 2016-17'],
  ['', 'ffl', 'Nitrozen', 'AdP Phosphorus', 'Potash', 'Total'],
  ['1', '2', '312', '313', '314', '315']],
 [['4.17 owing Seeds Distribution',
   '4.17 owing Seeds Distribution',
   '4.17 owing Seeds Distribution',
   '4.17 owing Seeds Distribution',
   '4.17 owing Seeds Distribution',
   '4.17 owing Seeds Distribution',
   '4.17 owing Seeds Distribution',
   '4.17 owing Seeds Distribution',
   '4.17 owing Seeds Distribution',
   '4.17 owing Seeds Distribution',
   '4.17 owing Seeds Distribution'],
  ['Sl.No.',
   'District',
   '2016-17 owing Seedsdistributed during 2016-17',
   '2016-17 owing Seedsdistributed during 2016-17',
   '2016-17 owing Seedsdistributed during 2016-17',
   '2016-17 owing Seedsdistributed during 2016-17',
   '2016-17 owing Seedsdistributed during 2016-17',
   '2016-17 owing Seedsdistributed during 2016-17',
   '2016-17 owing Seedsdistributed during 2016-17',
   '2016-17 owing Seedsdistributed during 2016-17',
   '2016-17 owing Seedsdistributed during 2016-17'],
  ['Sl.No.', 'District', '', '', '', '', '', '', '', '', ''],
  ['Sl.No.',
   'District',
   'Paddy',
   'Wheat',
   'Jowar',
   'Ragi',
   'Maize',
   'Bajra',
   'Bengal Gram',
   'Safflower',
   'Tur'],

In [13]:
def add_space_before_year(input_string):
    # Regular expression to find a year in 'yyyy' format with an optional alphabet character before it
    pattern = re.compile(r'([a-zA-Z])?(\d{4})')
    
    # Function to add space between alphabet character and year
    def replace(match):
        alphabet_part, year_part = match.groups()
        if alphabet_part:
            return f'{alphabet_part} {year_part}'
        else:
            return year_part

    # Using re.sub() to apply the replacement function to the input string
    result = pattern.sub(replace, input_string)

    return result

In [14]:
def remove_before_all_occurrence(input_string):
    # Regular expression to match numbers with dot similar to dd.dd, d.d, d.dd, or dd.d
    pattern = re.compile(r'\b(\d\.\d|\d{2}\.\d|\d\.\d{2}|\d{2}\.\d{2})\b')

    # Find all occurrences of the pattern in the input string
    matches = list(pattern.finditer(input_string))

    # If there are at least two occurrences of the pattern, remove everything before the second occurrence
    for i in range(len(matches)):
        second_occurrence_index = matches[i].start()
        input_string = input_string[second_occurrence_index:]

    return input_string.strip()

In [15]:
def convert_uppercase_to_camel_case(input_string):
    words = input_string.split()
    result_words = [word.capitalize() if word.isupper() else word for word in words]
    result_string = ' '.join(result_words)
    return result_string

In [16]:
def add_space_before_camelcase(input_string):
    # Use regular expression to find camel case words
    camelcase_pattern = re.compile(r'(?<=[a-z])(?=[A-Z])')
    result_string = camelcase_pattern.sub(' ', input_string)
    return result_string

In [17]:
def remove_extra_spaces(input_string):
    # Use regular expression to replace consecutive white spaces with a single space
    cleaned_string = re.sub(r'\s+', ' ', input_string)
    return cleaned_string.strip()

In [18]:
def add_space_before_word_with_condition(input_string):
    # Use regular expression to find words preceded by a number or special character
    pattern = re.compile(r'(?<=[%])\b(\w+)\b', flags=re.IGNORECASE)

    # Using re.sub() to add space before matched words
    result_string = pattern.sub(lambda x: ' ' + x.group(1), input_string)

    return result_string

In [19]:
def replace_words_with_blank(input_string, words_to_replace):
    # Constructing a regular expression pattern to match any of the words in the set
    # pattern = re.compile(r'\b(?:' + '|'.join(re.escape(word) for word in words_to_replace) + r')\b', flags=re.IGNORECASE)
    pattern = re.compile(r'(?<!\S)(?:' + '|'.join(re.escape(word) for word in words_to_replace) + r')(?!\S)', flags=re.IGNORECASE)

    # Using re.sub() to replace matched words with blank
    result = pattern.sub('', input_string)

    return result.strip()

In [20]:
words_to_replace = ['.CA', '.Dg', '.G.S', '.Jfl', '.Q.', '.ffl', '1 2', '1-10', '2 01', '2006 jAz 2016', '2011 twAi rAi AaP fiU', '2011 twAi zsj wAi EAzs %', '20112.2', '20112.6', '2011g', '24 7', '31.03.2017', '31.3.201', '31.3.2017', '31.3.2017.', '33 jAz 6', '6 jAz 1', '6 jAz 14', '6 wAU', 'A.ffl', 'A.g', 'AdP', 'Adg', 'Affl', 'Afi', 'Afli', 'Aid', 'Arg', 'Azs', 'CAU', 'CAZ', 'CAv', 'CAw', 'CAz', 'Cfi', 'CrP', 'Dfi', 'Dfl', 'E.J .n. .Dg .Jfl .JA.', 'EAf', 'Efi', 'Efl', 'JfiP', 'Jfl', 'KfiQ', 'MlM', 'Pfi', 'QAi', 'Raing', 'Rfl', 'SQA', 'Three', 'VAi', 'dfl', 'eng cy.U', 'ffl', 'fiAi', 'fiP', 'fiQ', 'fiQAi', 'fiU', 'fig', 'fl.', 'gLi', 'gMl', 'jAU', 'jAi', 'lion nit', 'ofD', 'rAi', 'tAwAi', 'tP', 'twAi', 'tzx', 'wAi', 'tzs']

In [21]:
def replace_words(input_string, word_replacements):
    # Constructing a regular expression pattern to match whole words in the set
    # pattern = re.compile(r'\b(?:' + '|'.join(re.escape(word) for word in word_replacements.keys()) + r')\b')
    pattern = re.compile(r'(?<!\S)(?:' + '|'.join(re.escape(word) for word in word_replacements.keys()) + r')(?!\S)')

    # Using re.sub() to replace matched words with their corresponding replacements
    result = pattern.sub(lambda x: word_replacements.get(x.group(), x.group()), input_string)

    return result

In [22]:
word_replacements = { "Husbandry5.1 2012" : "Husbandry 5.1", "animalstreated" : "animals treated", "Productionof" : "Production of", "terinary" : "Veterinary", "erinary" : "Veterinary", "KVS" : "KVS/RL", "Mathsasrayascheme" : "Mathsasraya scheme", "Fishcatch" : "Fish catch", "Productio" : "Production", "5.1 2012" : "5.1", "31.3.2017" : "31-3-2017" }

In [23]:
def process_data(input_data):
    for k in range(len(input_data)):
        for i in range(len(input_data[k])):
            for j in range(len(input_data[k][i])):
                #print(k,i,j,input_data[k][i][j])

                input_data[k][i][j] = add_space_before_year(input_data[k][i][j])
                input_data[k][i][j] = replace_words_with_blank(input_data[k][i][j], words_to_replace)
                input_data[k][i][j] = replace_words(input_data[k][i][j], word_replacements)
                input_data[k][i][j] = remove_before_all_occurrence(input_data[k][i][j])
                input_data[k][i][j] = add_space_before_camelcase(input_data[k][i][j])
                input_data[k][i][j] = convert_uppercase_to_camel_case(input_data[k][i][j])
                input_data[k][i][j] = remove_extra_spaces(input_data[k][i][j])
                input_data[k][i][j] = add_space_before_word_with_condition(input_data[k][i][j])

In [24]:
process_data(output_list)
output_list

[[['5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos',
   '5.1 Livestock Census 2012 In Nos'],
  ['',
   '',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012'],
  ['',
   '',
   'Cattle',
   'Cattle',
   'Cattle',
   'Cattle',
   'Buffaloes',
   'Sheeps',
   'Sheeps',
   'Sheeps',
   'Sheeps'],
  ['',
   '',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total',
   'Buffaloes',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total'],
  ['1', '2', '351', '352', '353', '354', '355', '356', '357', '358', '359']],
 [['5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012'],
  ['Sl.No.',
   'District',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012'],
  ['Sl.No.', 'District', 'Goats', 'Pigs', 'Pigs', 'Pigs', 'Pigs'],
  ['Sl.No.',
   'District',
   'Goats',
   'Indigenious',
   'Exotic',
   'Cross Breed',
   'Total'],
  ['1', '2', '360', '361', '362', '363', '364']],
 [['5.3 Artificial Insemination and Dairy Production Year 2016-17',
   '5.3 Artificial Insemination and Dairy Production Year 2016-17',
   '5.3 Artificial Insemination and Dairy Production Year 2016-17',
   '5.3 Artificial Insemination and Dairy Production Year 2016-17',
   '5.3 Artificial Insemination and Dairy Production Year 2016-17',
   '5.3 Artificial Insemination and Dairy Production Year 2016-17',
   '5.3 Artificial Insemination and Dairy Production Year 2016-17'],
  ['',
   'f Ufl',
   'Artificial Insemination Done Numbers',
   'No.of animals treated',
   'Production of Milk in Thousand Tonnes',
   'Production of Eggs. in Lakhs Nos',
   'Meat Production in Tonnes'],
  ['1', '2', '377', '378', '379', '380', '381']],
 [['5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012',
   '5.1 Livestock Census 2012'],
  ['',
   '',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012',
   'Livestock Census 2012'],
  ['', '', 'Rabbits', 'Dogs', 'Others', 'Total Live Stock', 'Poultry'],
  ['1', '2', '365', '366', '367', '368', '369']],
 [['5.2 Veterinary Hospitals on In Nos.',
   '5.2 Veterinary Hospitals on In Nos.',
   '5.2 Veterinary Hospitals on In Nos.',
   '5.2 Veterinary Hospitals on In Nos.',
   '5.2 Veterinary Hospitals on In Nos.',
   '5.2 Veterinary Hospitals on In Nos.',
   '5.2 Veterinary Hospitals on In Nos.',
   '5.2 Veterinary Hospitals on In Nos.',
   '5.2 Veterinary Hospitals on In Nos.'],
  ['Sl.No',
   'District',
   'Veterinary Institutions',
   'Veterinary Institutions',
   'Veterinary Institutions',
   'Veterinary Institutions',
   'Veterinary Institutions',
   'Veterinary Institutions',
   'Veterinary Institutions'],
  ['Sl.No',
   'District',
   'Veterinary Hospitals Kvs/rl',
   'Dispensaries',
   'Primary Veterinary Centres',
   'Mobile Dispensaries',
   'Artificial Insemination Centres',
   'Others',
   'Total'],
  ['1', '2', '370', '371', '372', '373', '374', '375', '376']],
 [['5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17'],
  ['',
   '',
   'Families involved in fisheries',
   'Families involved in fisheries',
   'No.of Beneficiaries under Mathsasraya scheme',
   'Fish lets In lakhs',
   'Fish markets No'],
  ['',
   '',
   'Full Time',
   'Part Time',
   'No.of Beneficiaries under Mathsasraya scheme',
   'Fish lets In lakhs',
   'Fish markets No'],
  ['1', '2', '389', '390', '391', '392', '393']],
 [['5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17',
   '5.4 Fisheries Year 2016-17'],
  ['Sl.No.',
   'District',
   'Fish catch in tonnes',
   'Ice Plants',
   'Ice Plants',
   'Cold storages',
   'Cold storages',
   'Total tanks for fisheries',
   'Total tanks for fisheries'],
  ['Sl.No.',
   'District',
   'Fish catch in tonnes',
   'No.',
   'Capacity Tonnes day',
   'No.',
   'Capacity Tonnes',
   'Panchayat Raj',
   'Minor Irrigation'],
  ['1', '2', '382', '383', '384', '385', '386', '387', '388']]]

In [25]:
#transpose the inner list
transp_list = [[list(pair) for pair in zip(*sublist)] for sublist in output_list]
transp_list

[[['5.1 Livestock Census 2012 In Nos', '', '', '', '1'],
  ['5.1 Livestock Census 2012 In Nos', '', '', '', '2'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Cattle',
   'Indigenious',
   '351'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Cattle',
   'Exotic',
   '352'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Cattle',
   'Cross Breed',
   '353'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Cattle',
   'Total',
   '354'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Buffaloes',
   'Buffaloes',
   '355'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Sheeps',
   'Indigenious',
   '356'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Sheeps',
   'Exotic',
   '357'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Sheeps',
   'Cross Breed',
   '358'],
  ['5.1 Livestock Census 2012 In Nos',
   'Livestock Census 2012',
   'Sheeps',
   'Total',
   '359']],
 [['5.1 Livestock Census 2012', 'Sl.No.', 'Sl.No.', 'Sl.No.', '1'],
  ['5.1 Livestock Census 2012', 'District', 'District', 'District', '2'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Goats',
   'Goats',
   '360'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Pigs',
   'Indigenious',
   '361'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Pigs',
   'Exotic',
   '362'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Pigs',
   'Cross Breed',
   '363'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Pigs',
   'Total',
   '364']],
 [['5.3 Artificial Insemination and Dairy Production Year 2016-17', '', '1'],
  ['5.3 Artificial Insemination and Dairy Production Year 2016-17',
   'f Ufl',
   '2'],
  ['5.3 Artificial Insemination and Dairy Production Year 2016-17',
   'Artificial Insemination Done Numbers',
   '377'],
  ['5.3 Artificial Insemination and Dairy Production Year 2016-17',
   'No.of animals treated',
   '378'],
  ['5.3 Artificial Insemination and Dairy Production Year 2016-17',
   'Production of Milk in Thousand Tonnes',
   '379'],
  ['5.3 Artificial Insemination and Dairy Production Year 2016-17',
   'Production of Eggs. in Lakhs Nos',
   '380'],
  ['5.3 Artificial Insemination and Dairy Production Year 2016-17',
   'Meat Production in Tonnes',
   '381']],
 [['5.1 Livestock Census 2012', '', '', '1'],
  ['5.1 Livestock Census 2012', '', '', '2'],
  ['5.1 Livestock Census 2012', 'Livestock Census 2012', 'Rabbits', '365'],
  ['5.1 Livestock Census 2012', 'Livestock Census 2012', 'Dogs', '366'],
  ['5.1 Livestock Census 2012', 'Livestock Census 2012', 'Others', '367'],
  ['5.1 Livestock Census 2012',
   'Livestock Census 2012',
   'Total Live Stock',
   '368'],
  ['5.1 Livestock Census 2012', 'Livestock Census 2012', 'Poultry', '369']],
 [['5.2 Veterinary Hospitals on In Nos.', 'Sl.No', 'Sl.No', '1'],
  ['5.2 Veterinary Hospitals on In Nos.', 'District', 'District', '2'],
  ['5.2 Veterinary Hospitals on In Nos.',
   'Veterinary Institutions',
   'Veterinary Hospitals Kvs/rl',
   '370'],
  ['5.2 Veterinary Hospitals on In Nos.',
   'Veterinary Institutions',
   'Dispensaries',
   '371'],
  ['5.2 Veterinary Hospitals on In Nos.',
   'Veterinary Institutions',
   'Primary Veterinary Centres',
   '372'],
  ['5.2 Veterinary Hospitals on In Nos.',
   'Veterinary Institutions',
   'Mobile Dispensaries',
   '373'],
  ['5.2 Veterinary Hospitals on In Nos.',
   'Veterinary Institutions',
   'Artificial Insemination Centres',
   '374'],
  ['5.2 Veterinary Hospitals on In Nos.',
   'Veterinary Institutions',
   'Others',
   '375'],
  ['5.2 Veterinary Hospitals on In Nos.',
   'Veterinary Institutions',
   'Total',
   '376']],
 [['5.4 Fisheries Year 2016-17', '', '', '1'],
  ['5.4 Fisheries Year 2016-17', '', '', '2'],
  ['5.4 Fisheries Year 2016-17',
   'Families involved in fisheries',
   'Full Time',
   '389'],
  ['5.4 Fisheries Year 2016-17',
   'Families involved in fisheries',
   'Part Time',
   '390'],
  ['5.4 Fisheries Year 2016-17',
   'No.of Beneficiaries under Mathsasraya scheme',
   'No.of Beneficiaries under Mathsasraya scheme',
   '391'],
  ['5.4 Fisheries Year 2016-17',
   'Fish lets In lakhs',
   'Fish lets In lakhs',
   '392'],
  ['5.4 Fisheries Year 2016-17', 'Fish markets No', 'Fish markets No', '393']],
 [['5.4 Fisheries Year 2016-17', 'Sl.No.', 'Sl.No.', '1'],
  ['5.4 Fisheries Year 2016-17', 'District', 'District', '2'],
  ['5.4 Fisheries Year 2016-17',
   'Fish catch in tonnes',
   'Fish catch in tonnes',
   '382'],
  ['5.4 Fisheries Year 2016-17', 'Ice Plants', 'No.', '383'],
  ['5.4 Fisheries Year 2016-17', 'Ice Plants', 'Capacity Tonnes day', '384'],
  ['5.4 Fisheries Year 2016-17', 'Cold storages', 'No.', '385'],
  ['5.4 Fisheries Year 2016-17', 'Cold storages', 'Capacity Tonnes', '386'],
  ['5.4 Fisheries Year 2016-17',
   'Total tanks for fisheries',
   'Panchayat Raj',
   '387'],
  ['5.4 Fisheries Year 2016-17',
   'Total tanks for fisheries',
   'Minor Irrigation',
   '388']]]

In [26]:
def find_table_details(input_string):
    # Regular expression to match numbers with dot similar to dd.dd, d.d, d.dd, or dd.d
    pattern = re.compile(r'\b(\d\.\d|\d{2}\.\d|\d\.\d{2}|\d{2}\.\d{2})\b')

    # Find all occurrences of the pattern in the input string
    matches = pattern.finditer(input_string)

    # Initialize variables to store the matches
    match_positions = []

    # Store the positions of the matches
    for match in matches:
        match_positions.append(match.start())

    # If there is at least one occurrence of the pattern
    if match_positions:
        table_id_index = match_positions[0]
        input_string = input_string[table_id_index:]  
        space_index = input_string.find(' ') 
        table_id = input_string[table_id_index:space_index].strip()
        table_name = input_string[space_index:].strip()
        return table_id, table_name    
    else:
        return None, None

In [27]:
def convert_to_number(string):
    try:
        number = int(string)
    except ValueError:
        try:
            number = float(string)
        except ValueError:
            raise ValueError("Input string is not a valid number")
    return number

In [28]:
chapter_id = 5
chapter_name = "Animal Husbandry"
#processing each column
def process_dictionary(input_data):
    df = pd.DataFrame(columns = ['Attr_id', 'Chapter_id', 'Chapter_name', 'Table_id', 'Table_name', 'Description'])
    for inner_list in input_data:
        table_id, table_name = find_table_details(inner_list[0][0])
        previd=0
        for data_list in inner_list:
            i=0
            attr_id=0
            description = ''
            prev = ''
            for data in reversed(data_list):
                if data == '1' or data == '2':
                    break
                i = i+1;
                if i == 1 and data!='' and (previd==0 or convert_to_number(data)!=previd):
                    attr_id = convert_to_number(data)
                    previd = convert_to_number(data)
                if i > 1 and i < len(data_list):
                    if description == '':
                        description = data
                        prev = data
                    else : 
                        if prev != data and data!='':
                            description = ','.join([description, data]) #description + ' ' + data
                            prev = data
            if attr_id != 0 and description != "" :
                row = {'Attr_id' : attr_id, 'Chapter_id' : chapter_id, 'Chapter_name' : chapter_name, 'Table_id' : table_id, 'Table_name' : table_name, 'Description' : remove_extra_spaces(description)}
                df.loc[len(df)] = row
    df = df.sort_values(by=['Attr_id'])
    df.to_csv('/home/riya/Downloads/ADT/Output_html_Chapter5/Chapter5_Attributes.csv', sep=';', index=False)
    df.to_csv('/home/riya/Downloads/ADT/Dictionary/Chapter5_Attributes.csv', sep=';', index=False)

In [29]:
process_dictionary(transp_list)

In [ ]:
#Not used
def remove_before_second_occurrence(input_string):
    # Regular expression to match numbers with dot similar to dd.dd, d.d, d.dd, or dd.d
    pattern = re.compile(r'\b(\d\.\d|\d{2}\.\d|\d\.\d{2}|\d{2}\.\d{2})\b')

    # Find all occurrences of the pattern in the input string
    matches = list(pattern.finditer(input_string))

    # If there are at least two occurrences of the pattern, remove everything before the second occurrence
    if len(matches) >= 2:
        second_occurrence_index = matches[1].start()
        input_string = input_string[second_occurrence_index:]

    return input_string.strip()