In [17]:
import pandas as pd
import os

In [18]:
data = pd.read_csv("./Data/Data_2015-16.csv", sep=";")

In [19]:
data

,1,2,3,4,5,6,7,8,9,10,...,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183
0,1,Bengaluru,27,198,27,96,4,16,562,26.0,...,0,73454,65846,14679,90,80615,65336,13465,544,79345
1,2,Bengaluru (R),17,183,17,105,4,7,957,94.0,...,0,133665,145020,33789,58,178867,125693,26260,81,152034
2,3,Ramanagara,18,244,18,126,4,6,820,52.0,...,0,183810,221460,49825,163,271448,167899,34406,261,202566
3,4,Chitradurga,22,312,22,189,6,8,948,115.0,...,0,402224,227197,63232,148,290577,438437,117797,4543,560777
4,5,Davangere,24,272,24,233,6,8,800,123.0,...,0,323462,226426,54817,1434,282677,333819,75816,4051,413686
5,6,Kolar,27,262,27,156,5,7,1608,189.0,...,0,189103,198213,38257,385,236855,200194,33277,452,233923
6,7,Chikkaballapura,26,249,26,157,6,8,1324,189.0,...,0,170903,178301,36054,107,214462,190840,33354,2163,226357
7,8,Shivamogga,37,377,37,271,7,9,1444,86.0,...,0,234739,169524,44187,297,214008,209674,51327,1297,262298
8,9,Tumakuru,50,568,50,331,10,12,2582,133.0,...,0,569246,326779,87403,246,414428,554996,120064,1328,676388
9,10,Chikkamagaluru,34,237,34,227,7,9,1022,95.0,...,0,273004,182860,39251,1366,223477,248508,51259,13609,313376
10,11,D. Kannada,17,289,17,230,5,41,331,NaN,...,0,164504,142792,65458,847,209097,121884,54614,1917,178415
11,12,Udupi,9,187,9,158,3,20,233,NaN,...,0,140138,112972,86970,543,200485,83068,64328,2221,149617
12,13,Hassan,38,411,38,267,8,11,2418,156.0,...,0,408846,341883,93219,579,435681,283395,76468,3637,363500
13,14,Kodagu,16,109,16,104,3,5,291,5.0,...,0,154512,57651,10803,427,68881,134872,22638,10351,167861
14,15,Mandya,45,437,45,234,7,9,1368,109.0,...,0,283994,280482,112940,2344,395766,246140,59378,3913,309431
15,16,Mysuru,33,448,33,266,7,19,1199,137.0,...,0,287892,301928,83606,192,385726,299508,67077,1945,368530
16,17,Chamarajnagar,16,231,16,130,4,5,428,81.0,...,0,170713,172297,39453,446,212196,176768,36726,1649,215143
17,18,Belagavi,35,554,35,502,10,31,1263,12.0,...,0,915122,487883,42948,104,530935,919337,69529,3423,992289
18,19,Vijayapura,20,240,20,213,5,6,679,13.0,...,0,844500,300565,41600,38,342203,844404,105256,672,950332
19,20,Bagalkote,18,251,18,198,6,15,613,11.0,...,0,439317,193388,34298,45,227731,419864,66307,945,487116
20,21,Dharwad,14,202,14,144,5,6,361,18.0,...,0,324861,124153,18868,204,143225,300444,41109,1425,342978
21,22,Gadag,11,197,11,122,5,9,322,15.0,...,0,353433,141852,21297,317,163466,343266,45196,1804,390266
22,23,Haveri,19,285,19,223,7,10,696,7.0,...,0,329205,198052,19944,355,218351,344691,30882,1345,376918
23,24,Uttara Kannada,35,243,35,231,11,18,1243,46.0,...,0,141272,149656,42658,508,192822,122369,26858,739,149966
24,25,Ballari,27,295,27,199,7,13,522,30.0,...,0,408028,211667,62557,911,275135,428891,104910,3725,537526
25,26,Bidar,29,330,29,186,5,7,595,25.0,...,0,373386,202413,48498,74,250985,372305,78541,929,451775
26,27,Kalaburagi,32,350,32,264,7,11,871,47.0,...,0,802627,324306,70921,270,395497,778237,157393,1907,937537
27,28,Yadagiri,16,172,16,123,3,7,487,26.0,...,0,339321,193095,33280,83,226458,377669,64335,268,442272
28,29,Raichur,37,280,37,181,5,9,815,69.0,...,0,511177,275390,56632,11,332033,591211,103988,588,695787
29,30,Koppal,20,161,20,153,4,5,595,34.0,...,0,362690,179033,39035,34,218102,366488,65766,1194,433448

In [20]:
type(data.columns[0])

str

In [21]:
for i in range(1,1183):
    if str(i) not in data.columns.tolist():
       print(i)

115
116
117
118
119
982
983
984
985
986
987
988
989
990
991

In [22]:
type(data.columns[0])

str