In [2]:
import pandas as pd
import os

In [7]:
data = pd.read_csv("./Data/Data_2015_16.csv", sep=";")

In [8]:
data

,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,...,1166.0,1167.0,1168.0,1169.0,1170.0,1171.0,1172.0,1173.0,1174.0,1175.0
0,1,Bagalkote,27,198,27,96,4,16,562,26.0,...,0,637,59497,13181,0,72678,60956,12498,0,73454
1,2,Bengaluru,17,183,17,105,4,7,957,94.0,...,0,4895,124141,28887,0,153028,110709,22956,0,133665
2,3,Bengaluru (R),18,244,18,126,4,6,820,52.0,...,0,1720,198469,44912,0,243381,152520,31290,0,183810
3,4,Belagavi,22,312,22,189,6,8,948,115.0,...,0,89834,157418,42442,0,199860,319437,82787,0,402224
4,5,Ballari,24,272,24,233,6,8,800,123.0,...,0,41711,173494,40915,0,214409,264944,58518,0,323462
5,6,Bidar,27,262,27,156,5,7,1608,189.0,...,0,9214,155442,29589,0,185031,162519,26584,0,189103
6,7,Vijayapura,26,249,26,157,6,8,1324,189.0,...,0,22756,129799,26124,0,155923,145628,25275,0,170903
7,8,Chamarajnagar,37,377,37,271,7,9,1444,86.0,...,0,4818,149163,38306,0,187469,189039,45700,0,234739
8,9,Chikkaballapura,50,568,50,331,10,12,2582,133.0,...,0,42090,263460,70278,0,333738,470507,98739,0,569246
9,10,Chikkamagaluru,34,237,34,227,7,9,1022,95.0,...,0,3990,159657,34217,0,193874,226429,46575,0,273004
10,11,Chitradurga,17,289,17,230,5,41,331,NaN,...,0,6585,127982,60111,0,188093,113134,51370,0,164504
11,12,D. Kannada,9,187,9,158,3,20,233,NaN,...,0,4895,105802,82793,0,188595,78271,61867,0,140138
12,13,Davangere,38,411,38,267,8,11,2418,156.0,...,0,5508,286820,82319,0,369139,340406,68440,0,408846
13,14,Dharwad,16,109,16,104,3,5,291,5.0,...,0,980,54373,10117,0,64490,132390,22122,0,154512
14,15,Gadag,45,437,45,234,7,9,1368,109.0,...,0,1538,250197,104467,0,354664,228930,55064,0,283994
15,16,Kalaburagi,33,448,33,266,7,19,1199,137.0,...,0,30592,218327,64297,0,282624,235016,52876,0,287892
16,17,Hassan,16,231,16,130,4,5,428,81.0,...,0,9747,130824,28808,0,159632,142479,28234,0,170713
17,18,Haveri,35,554,35,502,10,31,1263,12.0,...,0,33433,435945,36165,0,472110,852930,62192,0,915122
18,19,Kodagu,20,240,20,213,5,6,679,13.0,...,0,5982,257931,34163,0,292094,752518,91982,0,844500
19,20,Kolar,18,251,18,198,6,15,613,11.0,...,0,17264,169114,27703,0,196817,381869,57448,0,439317
20,21,Koppal,14,202,14,144,5,6,361,18.0,...,0,9112,115766,17131,0,132897,286246,38615,0,324861
21,22,Mandya,11,197,11,122,5,9,322,15.0,...,0,14591,124507,17582,0,142089,313372,40061,0,353433
22,23,Mysuru,19,285,19,223,7,10,696,7.0,...,0,25014,167285,16182,0,183467,302835,26370,0,329205
23,24,Raichur,35,243,35,231,11,18,1243,46.0,...,0,2632,142690,40149,0,182839,116394,24878,0,141272
24,25,Ramanagara,27,295,27,199,7,13,522,30.0,...,0,75316,151528,44775,0,196303,327487,80541,0,408028
25,26,Shivamogga,29,330,29,186,5,7,595,25.0,...,0,36188,158979,39440,0,198419,306863,66523,0,373386
26,27,Tumakuru,32,350,32,264,7,11,871,47.0,...,0,8130,263104,58000,0,321104,666131,136496,0,802627
27,28,Udupi,16,172,16,123,3,7,487,26.0,...,0,38537,137603,24398,0,162001,288377,50944,0,339321
28,29,Uttara Kannada,37,280,37,181,5,9,815,69.0,...,0,115831,188057,41552,0,229609,430813,80364,0,511177
29,30,Yadagiri,20,161,20,153,4,5,595,34.0,...,0,41629,145644,30996,0,176640,307989,54701,0,362690

In [17]:
for i in range(1,1183):
    if str(float(i)) not in data.columns.tolist():
       print(i)

115
116
117
118
119
358
359
364
464
465
466
467
468
469
987
988
989
990
991
1000
1001
1002
1003
1004
1005
1006
1007
1176
1177
1178
1179
1180
1181
1182

In [15]:
type(data.columns[0])

str