In [1]:
!pip install --upgrade gensim -q
!pip install matplotlib -q
!pip install spacy -q

In [2]:
import gensim
from gensim.models import word2vec
from gensim.models.word2vec import Word2Vec
import matplotlib.pyplot as plt
import spacy
import string
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/usr/lib/python3/dist-packages/paramiko/transport.py:237: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

In [3]:
from gensim.models import KeyedVectors
wv = KeyedVectors.load('vectors.kv')

In [4]:
def sent_vec(sent):
    vector_size = wv.vector_size
    wv_res = np.zeros(vector_size)
    # print(wv_res)
    ctr = 1
    for w in sent:
        if w in wv:
            ctr += 1
            wv_res += wv[w]
    wv_res = wv_res/ctr
    return wv_res

In [5]:
nlp = spacy.load('/home/riya/anaconda3/lib/python3.11/site-packages/en_core_web_sm/en_core_web_sm-3.7.1')
stop_words = nlp.Defaults.stop_words
print(stop_words)
punctuations = string.punctuation
print(punctuations)

{'namely', 'itself', 'sometimes', 'should', 'thence', 'not', 'has', 'such', 'those', "'ll", 'are', 'already', 'behind', 'perhaps', 'also', 'fifteen', 'give', 'ever', 'its', 'whole', '’s', 'nor', 'other', 'therein', 'beside', 'ourselves', 'last', '‘d', 'seemed', 'either', 'per', 'becomes', 'put', 'ten', 'together', 'anywhere', 'formerly', 'very', 'after', 'two', 'who', 'the', 'beyond', "'ve", 'anyway', 'used', 'twelve', 'enough', 'being', 'get', 'only', 'elsewhere', 'show', 'ca', 'though', 'anything', 'everyone', 'you', '’m', 'please', 'becoming', 'why', 'that', 'never', 'seeming', 'bottom', 'over', 'might', 'whenever', 'this', 'she', 'unless', 'above', 'some', 'others', 'whereupon', 'it', 'may', 'via', 'by', 'off', '’ll', 'since', 'still', 'made', 'except', 'themselves', 'have', 'hundred', 'but', 'whom', 'herself', 'down', 'yet', 'for', 'thru', 'an', 'see', 'first', 'much', 'when', 'whereas', 'to', 'same', 'both', 'yours', 'if', 'forty', 'just', 'him', 'beforehand', 'besides', 'indeed', 'hers', 'somehow', 'would', 'top', '’d', 'now', 'where', 'another', 'could', 'often', 'through', 'throughout', 'many', 'four', 'any', 'latterly', 'was', 'sometime', 'take', 'become', '‘s', 'around', 'up', 'too', 'move', 'during', 'nowhere', 'under', 'something', 'myself', 'part', 'anyone', 'empty', 'nobody', 'no', 'whither', 'thus', 'here', 'ours', 'almost', 'although', "'m", 'always', 'using', 'former', 'back', 'whereafter', 'due', 'how', 'n’t', 'or', 'front', 'his', 'must', 'call', 'toward', 'thereafter', 'will', 'amongst', 'noone', 'within', 'doing', 'fifty', 'everything', 'yourselves', 'until', "'re", 'of', 'anyhow', 'say', 'he', 'from', 'whoever', 'hereby', 'three', 'seems', 'more', 'does', 'most', 'i', 'least', 'our', 'six', 'every', 'however', 'upon', 'less', 'several', 'on', 'been', 'then', 'against', 'among', 'these', 'quite', 'full', "n't", 'without', 'seem', 'me', 'them', 'mostly', 'do', 'as', 'meanwhile', 'your', 'further', "'d", 'eleven', 'none', 'regarding', '’re', 'one', 'nothing', 'than', 'all', 'moreover', 'whatever', 'so', 'my', 'onto', 'yourself', 'which', 'about', 'can', 'because', 'again', 'with', 'third', 'did', 'neither', 'hereupon', 'at', 'go', 'wherever', 'own', 'n‘t', 'even', 'someone', 'hereafter', '’ve', 'be', 'five', 'nine', 'afterwards', 'had', 'we', 'their', 'whether', 'below', 'thereby', 'us', 'whose', 'mine', 'amount', 'is', 'next', 'side', 'nevertheless', 'sixty', 'eight', 'each', 'along', 'twenty', 'out', 'rather', 'whereby', 'wherein', 'really', 'there', 'well', 'few', 'various', 'into', 'towards', 'therefore', 'cannot', 'serious', 'across', 'somewhere', 'else', 'became', 'everywhere', 'done', 'her', 'keep', 'once', 'alone', 're', 'latter', 'were', '‘ll', 'they', "'s", 'otherwise', 'while', 'whence', '‘m', 'make', 'am', '‘re', 'before', 'a', 'in', 'name', 'herein', 'thereupon', '‘ve', 'and', 'between', 'hence', 'what', 'himself'}
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [6]:
# Creating our tokenizer function
def spacy_tokenizer(sentence):
    # Creating our token object, which is used to create documents with linguistic annotations.
    doc = nlp(sentence)



    #print(doc)
    #print(type(doc))

    # Lemmatizing each token and converting each token into lowercase
    mytokens = [ word.lemma_.lower().strip() for word in doc ]

    #print(mytokens)

    # Removing stop words
    mytokens = [ word for word in mytokens if word not in stop_words and word not in punctuations ]

    # return preprocessed list of tokens
    return mytokens

In [7]:
# Function to remove duplicates from a list and return a list of unique words
def remove_duplicates(word_list):
    return list(set(word_list))

In [8]:
data = pd.read_csv("Attributes_2016_17.csv", sep=";")

In [9]:
data

,Attr_id,Chapter_id,Chapter_name,Table_id,Table_name,Description
0,3.0,1,General Information,1.1,Nada Offices Village Accountant Circles Hoblie...,Nada Offices
1,4.0,1,General Information,1.1,Nada Offices Village Accountant Circles Hoblie...,Va Circles
2,5.0,1,General Information,1.1,Nada Offices Village Accountant Circles Hoblie...,Hoblies
3,6.0,1,General Information,1.1,Nada Offices Village Accountant Circles Hoblie...,Grama Panchayaths
4,7.0,1,General Information,1.1,Nada Offices Village Accountant Circles Hoblie...,No.of Taluks
...,...,...,...,...,...,...
1162,1169.0,18,Additional information,18.1,Agricultural Land Holdings And Area per 2010-1...,"Total,Number,Total Agrl. Land Holder Total"
1163,1170.0,18,Additional information,18.1,Agricultural Land Holdings And Area per 2010-1...,"Male,Area,Total Agrl. Land Holder Total"
1164,1171.0,18,Additional information,18.1,Agricultural Land Holdings And Area per 2010-1...,"Female,Area,Total Agrl. Land Holder Total"
1165,1172.0,18,Additional information,18.1,Agricultural Land Holdings And Area per 2010-1...,"Institutions,Area,Total Agrl. Land Holder Total"
1166,1173.0,18,Additional information,18.1,Agricultural Land Holdings And Area per 2010-1...,"Total,Area,Total Agrl. Land Holder Total"

In [10]:
data.columns

Index(['Attr_id', 'Chapter_id', 'Chapter_name', 'Table_id', 'Table_name',
       'Description'],
      dtype='object')

In [11]:
data.drop(['Attr_id', 'Table_id', 'Description'],axis=1,inplace=True)

In [12]:
data

,Chapter_id,Chapter_name,Table_name
0,1,General Information,Nada Offices Village Accountant Circles Hoblie...
1,1,General Information,Nada Offices Village Accountant Circles Hoblie...
2,1,General Information,Nada Offices Village Accountant Circles Hoblie...
3,1,General Information,Nada Offices Village Accountant Circles Hoblie...
4,1,General Information,Nada Offices Village Accountant Circles Hoblie...
...,...,...,...
1162,18,Additional information,Agricultural Land Holdings And Area per 2010-1...
1163,18,Additional information,Agricultural Land Holdings And Area per 2010-1...
1164,18,Additional information,Agricultural Land Holdings And Area per 2010-1...
1165,18,Additional information,Agricultural Land Holdings And Area per 2010-1...
1166,18,Additional information,Agricultural Land Holdings And Area per 2010-1...

In [14]:
new_df = data.groupby(['Chapter_id', 'Chapter_name'])['Table_name'].apply(lambda x: ', '.join(x)).reset_index()
new_df

,Chapter_id,Chapter_name,Table_name
0,1,General Information,Nada Offices Village Accountant Circles Hoblie...
1,2,Area and Population,Population and percentage share to total Popul...
2,3,Rainfall,No.of Rainguage Raingauge Stations Annual Norm...
3,4,"Agriculture, Horticulture and Sericulture","Land Utilisation in Hectares, Land Utilisation..."
4,5,Animal Husbandry,"Livestock Census 2012 In Nos, Livestock Census..."
5,6,Industries,Number of Factories Employees on 31-3-2017 In ...
6,7,Banks,Flow of Bank Credit to Agriculture and Allied ...
7,8,Co-operation and Agricultural Marketing,"D.c.c. Banks on 31-3-2017 Rs.in lakhs, D.c.c. ..."
8,9,TRANSPORT AND COMMUNICATION,"Motor Vehicles on 31-03-2017, Motor Vehicles o..."
9,10,Education,"Literates rates per 2011 Census, Literates rat..."
10,11,Health & Family welfare Services,Taluk District Autonomous Teaching Other Hospi...
11,12,Social Welfare,Scheduled Caste Student Hostels As on 31-3-201...
12,13,Women & Child Development,Stree Shakti Self Help Groups and Members Year...
13,14,Rural Development & Panchayat Raj,Forest Area E.s.t.p and N.r.l.m Year 2016-17 I...
14,15,Housing,Census Houses and their uses to which they put...
15,16,Energy,No.of Electrified Villages Hamlets & Ip Sets 2...
16,17,Miscellaneous,Excise Shop and Consumption of Liquor Year 201...
17,18,Additional information,Agricultural Land Holdings And Area per 2010-1...

In [15]:
new_df.columns = ['Chapter_id', 'Chapter_name', 'Description']

In [16]:
new_df['new_description'] = new_df['Description'].apply(spacy_tokenizer)

In [17]:
# Apply the function to create the new column
new_df['tokens'] = new_df['new_description'].apply(remove_duplicates)

In [18]:
new_df['vec'] = new_df['tokens'].apply(sent_vec)

In [19]:
new_df

,Chapter_id,Chapter_name,Description,new_description,tokens,vec
0,1,General Information,Nada Offices Village Accountant Circles Hoblie...,"[nada, offices, village, accountant, circles, ...","[karnataka, villages, shops, hoblies, inhabit,...","[0.05575314083614865, 0.04994325380067568, 0.0..."
1,2,Area and Population,Population and percentage share to total Popul...,"[population, percentage, share, total, populat...","[proportion, tribes, numbers, urban, projected...","[0.06776674332157258, 0.014455487651209678, 0...."
2,3,Rainfall,No.of Rainguage Raingauge Stations Annual Norm...,"[no.of, rainguage, raingauge, stations, annual...","[raingauge, annual, normal, rainfall, rain, no...","[-0.006795247395833333, 0.1025119357638889, -0..."
3,4,"Agriculture, Horticulture and Sericulture","Land Utilisation in Hectares, Land Utilisation...","[land, utilisation, hectares, land, utilisatio...","[important, hectare, fruits, fertilizer, princ...","[0.06843118106617647, 0.11398135914522059, 0.0..."
4,5,Animal Husbandry,"Livestock Census 2012 In Nos, Livestock Census...","[livestock, census, 2012, nos, livestock, cens...","[livestock, 17, artificial, insemination, fish...","[0.012959798177083334, 0.060602823893229164, -..."
5,6,Industries,Number of Factories Employees on 31-3-2017 In ...,"[number, factory, employee, 31, 3, 2017, numbe...","[3, numbers, plots, number, 2017, setup, facto...","[0.1188341776529948, 0.039471705754597984, 0.0..."
6,7,Banks,Flow of Bank Credit to Agriculture and Allied ...,"[flow, bank, credit, agriculture, allied, sect...","[wise, 3, number, 2017, sector, schedule, -mar...","[0.021759033203125, 0.003392999822443182, -0.0..."
7,8,Co-operation and Agricultural Marketing,"D.c.c. Banks on 31-3-2017 Rs.in lakhs, D.c.c. ...","[d.c.c, bank, 31, 3, 2017, rs.in, lakh, d.c.c,...","[bank, co, pld, kscard, credit, 3, lakh, d.c.c...","[0.04721901633522727, 0.03069513494318182, -0...."
8,9,TRANSPORT AND COMMUNICATION,"Motor Vehicles on 31-03-2017, Motor Vehicles o...","[motor, vehicles, 31, 03, 2017, motor, vehicle...","[road, p.w.d, numbers, exchanges, rural, numbe...","[0.0384368896484375, 0.055701255798339844, -0...."
9,10,Education,"Literates rates per 2011 Census, Literates rat...","[literate, rate, 2011, census, literates, rate...","[u, engineering, literates, schools, p, 14, ce...","[0.02491446102366728, 0.00872802734375, 0.0547..."
10,11,Health & Family welfare Services,Taluk District Autonomous Teaching Other Hospi...,"[taluk, district, autonomous, teaching, hospit...","[clinics, 3, allopathy, pro, health, 2017, cen...","[0.002758026123046875, 0.032946374681260854, 0..."
11,12,Social Welfare,Scheduled Caste Student Hostels As on 31-3-201...,"[schedule, caste, student, hostels, 31, 3, 201...","[tribes, 3, schools, numbers, minorities, numb...","[0.0309912109375, 0.039817276000976565, 0.0852..."
12,13,Women & Child Development,Stree Shakti Self Help Groups and Members Year...,"[stree, shakti, self, help, groups, member, ye...","[member, received, supplementary, anganawadi, ...","[0.06333060886548914, 0.029185419497282608, 0...."
13,14,Rural Development & Panchayat Raj,Forest Area E.s.t.p and N.r.l.m Year 2016-17 I...,"[forest, area, e.s.t.p, n.r.l.m, year, 2016, 1...","[rural, raj, schemes, development, progress, d...","[-0.03283110119047619, 0.04975055512927827, 0...."
14,15,Housing,Census Houses and their uses to which they put...,"[census, houses, use, 2011, census, census, ho...","[lighting, ashraya, census, rural, number, sch...","[0.095086669921875, 0.05711708068847656, -0.01..."
15,16,Energy,No.of Electrified Villages Hamlets & Ip Sets 2...,"[no.of, electrified, villages, hamlets, ip, se...","[17, villages, nos, electricity, electrified, ...","[0.14857066761363635, 0.08722478693181818, 0.0..."
16,17,Miscellaneous,Excise Shop and Consumption of Liquor Year 201...,"[excise, shop, consumption, liquor, year, 2016...","[17, excise, birth, social, death, nos, 3, liq...","[0.136962890625, 0.010990687779017858, -0.0154..."
17,18,Additional information,Agricultural Land Holdings And Area per 2010-1...,"[agricultural, land, holdings, area, 2010, 11,...","[holdings, agri, agricultural, 11, census, lan...","[0.0587310791015625, 0.0652008056640625, 0.029..."

In [20]:
ll = new_df['tokens'].loc[4]

In [21]:
ll

['livestock',
 '17',
 'artificial',
 'insemination',
 'fisheries',
 'nos',
 '2016',
 '2012',
 'veterinary',
 'production',
 'census',
 'hospitals',
 'year',
 'dairy']

In [22]:
# Extract vectors from DataFrame
vectors = np.array(new_df['vec'].to_list())

# Compute cosine similarity between vectors
similarity_matrix = cosine_similarity(vectors, vectors)

# Convert the similarity matrix to a DataFrame for visualization
similarity_df = pd.DataFrame(similarity_matrix, columns=range(18), index=range(18))

In [23]:
similarity_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,1.000000,0.632134,0.439693,0.548089,0.516213,0.645303,0.602226,0.531308,0.626798,0.617088,0.716271,0.629362,0.616865,0.751582,0.668286,0.641409,0.661237,0.591930
1,0.632134,1.000000,0.465156,0.477877,0.468726,0.568870,0.611485,0.481663,0.548662,0.673630,0.559439,0.800393,0.557968,0.573455,0.585087,0.477038,0.556010,0.491174
2,0.439693,0.465156,1.000000,0.457992,0.374695,0.425113,0.468931,0.257804,0.458351,0.378670,0.339830,0.371054,0.335444,0.435548,0.428760,0.363418,0.370623,0.352476
3,0.548089,0.477877,0.457992,1.000000,0.611577,0.638450,0.626500,0.470753,0.449167,0.461682,0.496304,0.429823,0.534221,0.631731,0.575589,0.486131,0.495388,0.659563
4,0.516213,0.468726,0.374695,0.611577,1.000000,0.505678,0.495408,0.390974,0.431766,0.489754,0.588843,0.429147,0.502560,0.566813,0.513608,0.460959,0.519719,0.596670
5,0.645303,0.568870,0.425113,0.638450,0.505678,1.000000,0.637031,0.473285,0.598907,0.539528,0.587650,0.583764,0.562594,0.660198,0.662207,0.557565,0.615025,0.544252
6,0.602226,0.611485,0.468931,0.626500,0.495408,0.637031,1.000000,0.651389,0.597118,0.563405,0.548787,0.586753,0.654822,0.588738,0.608699,0.418019,0.534727,0.593210
7,0.531308,0.481663,0.257804,0.470753,0.390974,0.473285,0.651389,1.000000,0.373024,0.496598,0.538630,0.473369,0.606779,0.474521,0.396727,0.354561,0.548435,0.313610
8,0.626798,0.548662,0.458351,0.449167,0.431766,0.598907,0.597118,0.373024,1.000000,0.488278,0.530744,0.531607,0.460650,0.643389,0.648120,0.556900,0.485174,0.494908
9,0.617088,0.673630,0.378670,0.461682,0.489754,0.539528,0.563405,0.496598,0.488278,1.000000,0.695805,0.780533,0.642805,0.560843,0.527114,0.436221,0.538718,0.419070
10,0.716271,0.559439,0.339830,0.496304,0.588843,0.587650,0.548787,0.538630,0.530744,0.695805,1.000000,0.643164,0.668658,0.714623,0.596115,0.513777,0.611142,0.440464
11,0.629362,0.800393,0.371054,0.429823,0.429147,0.583764,0.586753,0.473369,0.531607,0.780533,0.643164,1.000000,0.608237,0.586791,0.564767,0.468931,0.531828,0.430688
12,0.616865,0.557968,0.335444,0.534221,0.502560,0.562594,0.654822,0.606779,0.460650,0.642805,0.668658,0.608237,1.000000,0.613899,0.600275,0.451705,0.596588,0.465005
13,0.751582,0.573455,0.435548,0.631731,0.566813,0.660198,0.588738,0.474521,0.643389,0.560843,0.714623,0.586791,0.613899,1.000000,0.767879,0.615602,0.630022,0.545269
14,0.668286,0.585087,0.428760,0.575589,0.513608,0.662207,0.608699,0.396727,0.648120,0.527114,0.596115,0.564767,0.600275,0.767879,1.000000,0.590518,0.605982,0.555812
15,0.641409,0.477038,0.363418,0.486131,0.460959,0.557565,0.418019,0.354561,0.556900,0.436221,0.513777,0.468931,0.451705,0.615602,0.590518,1.000000,0.579112,0.400251
16,0.661237,0.556010,0.370623,0.495388,0.519719,0.615025,0.534727,0.548435,0.485174,0.538718,0.611142,0.531828,0.596588,0.630022,0.605982,0.579112,1.000000,0.374880
17,0.591930,0.491174,0.352476,0.659563,0.596670,0.544252,0.593210,0.313610,0.494908,0.419070,0.440464,0.430688,0.465005,0.545269,0.555812,0.400251,0.374880,1.000000

In [24]:
sdg = pd.read_csv('sdg_data_vec.csv', sep=";")
sdg

,Unnamed: 0,Goal No.,Goal,Targets,new_targets,tokens,vec
0,0,1,End poverty in all its forms everywhere,"By 2030, eradicate extreme poverty for all peo...","['2030', 'eradicate', 'extreme', 'poverty', 'p...","['child', 'people', 'microfinance', 'particula...",[ 1.99330318e-02 3.61419281e-02 -5.63049316e-...
1,1,2,"End hunger, achieve food security and improved...","By 2030, end hunger and ensure access by all p...","['2030', 'end', 'hunger', 'ensure', 'access', ...","['child', 'volatility', 'research', 'prevent',...",[-3.81049859e-02 4.79703200e-02 -2.91772140e-...
2,2,3,Ensure healthy lives and promote well-being fo...,"By 2030, reduce the maternal mortality ratio t...","['2030', 'reduce', 'maternal', 'mortality', 'r...","['child', 'road', 'implementation', 'research'...",[-4.11676887e-02 5.00096183e-02 2.76913242e-...
3,3,4,Ensure inclusive and equitable quality educati...,"By 2030, ensure that all girls and boys comple...","['2030', 'ensure', 'girl', 'boy', 'complete', ...","['child', 'people', 'substantially', 'scientif...",[-0.04538551 0.00699968 0.01054353 0.049253...
4,4,5,Achieve gender equality and empower all women ...,End all forms of discrimination against all wo...,"['end', 'form', 'discrimination', 'woman', 'gi...","['child', 'decision', 'sphere', 'value', 'shar...",[-3.91934204e-02 1.35421753e-02 4.12231445e-...
5,5,6,"Ensure access to affordable, reliable, sustain...","By 2030, ensure universal access to affordable...","['2030', 'ensure', 'universal', 'access', 'aff...","['energy', 'affordable', 'modern', 'service', ...",[-0.05875651 -0.05223253 -0.00542535 -0.023552...
6,6,6,Ensure availability and sustainable management...,"By 2030, achieve universal and equitable acces...","['2030', 'achieve', 'universal', 'equitable', ...","['material', 'people', 'drinking', 'substantia...",[-0.08247549 0.06165522 0.01714464 0.016053...
7,7,7,"Ensure access to affordable, reliable, sustain...","By 2030, ensure universal access to affordable...","['2030', 'ensure', 'universal', 'access', 'aff...","['energy', 'accordance', 'research', 'double',...",[-0.11421156 0.03368835 0.02188492 0.011013...
8,8,8,"Promote sustained, inclusive and sustainable e...",Sustain per capita economic growth in accordan...,"['sustain', 'capita', 'economic', 'growth', 'a...","['child', 'devise', 'worker', 'people', 'secur...",[-2.73829869e-02 2.83027528e-02 -1.50217934e-...
9,9,9,"Build resilient infrastructure, promote inclus...","Develop quality, reliable, sustainable and res...","['develop', 'quality', 'reliable', 'sustainabl...","['research', 'worker', 'double', 'chain', 'peo...",[-7.18635718e-02 2.55494714e-02 -1.83308919e-...
10,10,10,Reduce inequality within the State,"By 2030, progressively achieve and sustain inc...","['2030', 'progressively', 'achieve', 'sustain'...","['disability', 'equality', 'equal', 'cent', 'e...",[-3.16180420e-02 2.00415039e-02 -1.74108887e-...
11,11,11,"Make cities and human settlements inclusive, s...","By 2030, ensure access for all to adequate, sa...","['2030', 'ensure', 'access', 'adequate', 'safe...","['child', 'positive', 'road', 'material', 'peo...",[-0.0478811 0.04508594 0.00164423 0.053786...
12,12,12,Ensure sustainable consumption and production\...,"By 2030, achieve the sustainable management an...","['2030', 'achieve', 'sustainable', 'management...","['harmony', 'cycle', 'chain', 'people', 'repor...",[-8.15658362e-02 5.97149393e-02 -2.35341943e-...
13,13,13,Take urgent action to combat climate change an...,Strengthen resilience and adaptive capacity to...,"['strengthen', 'resilience', 'adaptive', 'capa...","['strengthen', 'awareness', 'integrate', 'rais...",[-1.02294922e-02 7.48250326e-02 5.90413411e-...
14,14,14,"Protect, restore and promote sustainable use o...","By 2020, ensure the conservation, restoration ...","['2020', 'ensure', 'conservation', 'restoratio...","['inland', 'implementation', 'prevent', 'neutr...",[-3.36039986e-02 7.86299818e-02 -7.76079133e-...
15,15,15,Promote peaceful and inclusive societies for s...,Significantly reduce all forms of violence and...,"['significantly', 'reduce', 'form', 'violence'...","['strengthen', 'trafficking', 'recovery', 'chi...",[-0.07061774 0.02596736 -0.00679421 0.033442...
16,16,16,Strengthen the means of implementation and rev...,"Strengthen domestic resource mobilization, inc...","['strengthen', 'domestic', 'resource', 'mobili...","['strengthen', 'building', 'fully', 'include',...",[-9.95303883e-02 3.47529393e-02 1.64196538e-...
17,17,17,"Data, monitoring and accountability","By 2020, enhance capacity-building support to ...","['2020', 'enhance', 'capacity', 'build', 'supp...","['disability', '2020', 'building', 'ethnicity'...",[-5.27105564e-02 -1.63410466e-02 -2.57464153e-...

In [25]:
# Convert string representations of vectors to actual NumPy arrays
sdg['vec'] = sdg['vec'].apply(lambda x: np.array([float(value) for value in x.strip('[]').split()]))
sdg

,Unnamed: 0,Goal No.,Goal,Targets,new_targets,tokens,vec
0,0,1,End poverty in all its forms everywhere,"By 2030, eradicate extreme poverty for all peo...","['2030', 'eradicate', 'extreme', 'poverty', 'p...","['child', 'people', 'microfinance', 'particula...","[0.0199330318, 0.0361419281, -0.00563049316, 0..."
1,1,2,"End hunger, achieve food security and improved...","By 2030, end hunger and ensure access by all p...","['2030', 'end', 'hunger', 'ensure', 'access', ...","['child', 'volatility', 'research', 'prevent',...","[-0.0381049859, 0.04797032, -0.029177214, 0.04..."
2,2,3,Ensure healthy lives and promote well-being fo...,"By 2030, reduce the maternal mortality ratio t...","['2030', 'reduce', 'maternal', 'mortality', 'r...","['child', 'road', 'implementation', 'research'...","[-0.0411676887, 0.0500096183, 0.0276913242, 0...."
3,3,4,Ensure inclusive and equitable quality educati...,"By 2030, ensure that all girls and boys comple...","['2030', 'ensure', 'girl', 'boy', 'complete', ...","['child', 'people', 'substantially', 'scientif...","[-0.04538551, 0.00699968, 0.01054353, 0.049253..."
4,4,5,Achieve gender equality and empower all women ...,End all forms of discrimination against all wo...,"['end', 'form', 'discrimination', 'woman', 'gi...","['child', 'decision', 'sphere', 'value', 'shar...","[-0.0391934204, 0.0135421753, 0.00412231445, 0..."
5,5,6,"Ensure access to affordable, reliable, sustain...","By 2030, ensure universal access to affordable...","['2030', 'ensure', 'universal', 'access', 'aff...","['energy', 'affordable', 'modern', 'service', ...","[-0.05875651, -0.05223253, -0.00542535, -0.023..."
6,6,6,Ensure availability and sustainable management...,"By 2030, achieve universal and equitable acces...","['2030', 'achieve', 'universal', 'equitable', ...","['material', 'people', 'drinking', 'substantia...","[-0.08247549, 0.06165522, 0.01714464, 0.016053..."
7,7,7,"Ensure access to affordable, reliable, sustain...","By 2030, ensure universal access to affordable...","['2030', 'ensure', 'universal', 'access', 'aff...","['energy', 'accordance', 'research', 'double',...","[-0.11421156, 0.03368835, 0.02188492, 0.011013..."
8,8,8,"Promote sustained, inclusive and sustainable e...",Sustain per capita economic growth in accordan...,"['sustain', 'capita', 'economic', 'growth', 'a...","['child', 'devise', 'worker', 'people', 'secur...","[-0.0273829869, 0.0283027528, -0.0150217934, 0..."
9,9,9,"Build resilient infrastructure, promote inclus...","Develop quality, reliable, sustainable and res...","['develop', 'quality', 'reliable', 'sustainabl...","['research', 'worker', 'double', 'chain', 'peo...","[-0.0718635718, 0.0255494714, -0.0183308919, 0..."
10,10,10,Reduce inequality within the State,"By 2030, progressively achieve and sustain inc...","['2030', 'progressively', 'achieve', 'sustain'...","['disability', 'equality', 'equal', 'cent', 'e...","[-0.031618042, 0.0200415039, -0.0174108887, 0...."
11,11,11,"Make cities and human settlements inclusive, s...","By 2030, ensure access for all to adequate, sa...","['2030', 'ensure', 'access', 'adequate', 'safe...","['child', 'positive', 'road', 'material', 'peo...","[-0.0478811, 0.04508594, 0.00164423, 0.0537863..."
12,12,12,Ensure sustainable consumption and production\...,"By 2030, achieve the sustainable management an...","['2030', 'achieve', 'sustainable', 'management...","['harmony', 'cycle', 'chain', 'people', 'repor...","[-0.0815658362, 0.0597149393, -0.00235341943, ..."
13,13,13,Take urgent action to combat climate change an...,Strengthen resilience and adaptive capacity to...,"['strengthen', 'resilience', 'adaptive', 'capa...","['strengthen', 'awareness', 'integrate', 'rais...","[-0.0102294922, 0.0748250326, 0.00590413411, 0..."
14,14,14,"Protect, restore and promote sustainable use o...","By 2020, ensure the conservation, restoration ...","['2020', 'ensure', 'conservation', 'restoratio...","['inland', 'implementation', 'prevent', 'neutr...","[-0.0336039986, 0.0786299818, -0.00776079133, ..."
15,15,15,Promote peaceful and inclusive societies for s...,Significantly reduce all forms of violence and...,"['significantly', 'reduce', 'form', 'violence'...","['strengthen', 'trafficking', 'recovery', 'chi...","[-0.07061774, 0.02596736, -0.00679421, 0.03344..."
16,16,16,Strengthen the means of implementation and rev...,"Strengthen domestic resource mobilization, inc...","['strengthen', 'domestic', 'resource', 'mobili...","['strengthen', 'building', 'fully', 'include',...","[-0.0995303883, 0.0347529393, 0.00164196538, 0..."
17,17,17,"Data, monitoring and accountability","By 2020, enhance capacity-building support to ...","['2020', 'enhance', 'capacity', 'build', 'supp...","['disability', '2020', 'building', 'ethnicity'...","[-0.0527105564, -0.0163410466, -0.0257464153, ..."

In [26]:
# Extract vectors from DataFrame
sdg_vectors = np.array(sdg['vec'].to_list())

# Compute cosine similarity between vectors
similarity_matrix_sdg = cosine_similarity(vectors, sdg_vectors)

# Convert the similarity matrix to a DataFrame for visualization
similarity_df_sdg = pd.DataFrame(similarity_matrix_sdg, columns=range(18), index=range(18))

In [27]:
similarity_df_sdg

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.530775,0.552858,0.523951,0.541510,0.541405,0.348986,0.534971,0.402298,0.520633,0.472797,0.511459,0.542025,0.486837,0.392781,0.517121,0.498363,0.417693,0.447861
1,0.604730,0.604097,0.589397,0.633101,0.606935,0.299889,0.524972,0.431043,0.577122,0.493922,0.681386,0.556326,0.491676,0.445181,0.530510,0.516164,0.393058,0.604610
2,0.387285,0.460929,0.407674,0.359182,0.330897,0.178941,0.439483,0.322757,0.367329,0.338450,0.363975,0.385763,0.391998,0.353337,0.423983,0.340604,0.279198,0.368824
3,0.502534,0.648674,0.524837,0.470023,0.467652,0.233914,0.566897,0.466298,0.544643,0.500665,0.425191,0.507123,0.553227,0.440196,0.594508,0.419840,0.446911,0.444600
4,0.413449,0.577666,0.541209,0.447592,0.458941,0.244514,0.497688,0.392738,0.458484,0.439672,0.403414,0.432346,0.479119,0.375555,0.508027,0.389608,0.385953,0.409910
5,0.545781,0.591485,0.519916,0.516548,0.498309,0.315530,0.537666,0.453724,0.584849,0.526455,0.474642,0.546822,0.540741,0.433321,0.495227,0.473278,0.426478,0.482447
6,0.662850,0.704364,0.624504,0.618444,0.629304,0.406666,0.625298,0.596629,0.683164,0.692868,0.595563,0.662585,0.643700,0.532698,0.617602,0.605031,0.608277,0.615198
7,0.433449,0.474618,0.425787,0.441282,0.425605,0.251466,0.376470,0.355759,0.461446,0.432382,0.431305,0.401982,0.394310,0.334771,0.385398,0.433438,0.415626,0.370864
8,0.533572,0.550380,0.541861,0.522798,0.519943,0.457338,0.551974,0.477749,0.505316,0.529876,0.472213,0.562395,0.487693,0.426641,0.503928,0.461246,0.450515,0.492957
9,0.569295,0.590028,0.603691,0.734682,0.567272,0.362706,0.531920,0.472917,0.609565,0.541234,0.596867,0.573032,0.517840,0.485162,0.475231,0.503685,0.467459,0.535422
10,0.603103,0.621876,0.708794,0.656669,0.631756,0.416598,0.603494,0.482423,0.603178,0.551171,0.561621,0.624044,0.575977,0.507811,0.543391,0.560789,0.519209,0.512740
11,0.553181,0.550796,0.537657,0.658831,0.556662,0.357039,0.500100,0.428733,0.550995,0.496103,0.618338,0.539891,0.457623,0.415886,0.484088,0.496854,0.386979,0.525073
12,0.649088,0.677264,0.626456,0.676725,0.658716,0.366890,0.578351,0.515804,0.668711,0.613401,0.617905,0.651025,0.602014,0.552665,0.583887,0.610612,0.601876,0.541180
13,0.606132,0.656414,0.629037,0.626820,0.610738,0.420759,0.710574,0.547090,0.631107,0.596616,0.531924,0.672542,0.636696,0.545514,0.648980,0.530715,0.554651,0.550416
14,0.646832,0.668978,0.628019,0.612800,0.597974,0.510909,0.696837,0.584552,0.622586,0.614963,0.555781,0.674863,0.643328,0.527794,0.619549,0.538523,0.537828,0.581160
15,0.403176,0.461862,0.421384,0.372190,0.392950,0.384590,0.464538,0.450374,0.435505,0.445514,0.364176,0.436754,0.451535,0.353521,0.434838,0.343345,0.359041,0.373602
16,0.490891,0.525273,0.554621,0.497203,0.538067,0.312013,0.443500,0.378119,0.521101,0.451890,0.553109,0.475209,0.482523,0.376107,0.429984,0.520420,0.411526,0.429348
17,0.494478,0.577295,0.465190,0.462148,0.488327,0.230434,0.520142,0.416746,0.501285,0.488701,0.435902,0.499555,0.477804,0.408003,0.561545,0.421559,0.426955,0.436861

In [28]:
# Initialize empty lists to store chapter_id and chapter_name
max_similarity_chapter_id = []
max_similarity_chapter_name = []

# Iterate through the rows of the similarity matrix
for row in similarity_matrix_sdg:
    # Find the index of the maximum similarity value in the row
    max_index = np.argmax(row)
    
    # Get the corresponding chapter_id and chapter_name from the sdg DataFrame
    chapter_id = new_df['Chapter_id'].loc[max_index]
    chapter_name = new_df['Chapter_name'].loc[max_index]
    
    # Append the chapter_id and chapter_name to the lists
    max_similarity_chapter_id.append(chapter_id)
    max_similarity_chapter_name.append(chapter_name)

# Add new columns to the sdg DataFrame
sdg['Max_similarity_chapter_id'] = max_similarity_chapter_id
sdg['Max_similarity_chapter_name'] = max_similarity_chapter_name

In [29]:
sdg

,Unnamed: 0,Goal No.,Goal,Targets,new_targets,tokens,vec,Max_similarity_chapter_id,Max_similarity_chapter_name
0,0,1,End poverty in all its forms everywhere,"By 2030, eradicate extreme poverty for all peo...","['2030', 'eradicate', 'extreme', 'poverty', 'p...","['child', 'people', 'microfinance', 'particula...","[0.0199330318, 0.0361419281, -0.00563049316, 0...",2,Area and Population
1,1,2,"End hunger, achieve food security and improved...","By 2030, end hunger and ensure access by all p...","['2030', 'end', 'hunger', 'ensure', 'access', ...","['child', 'volatility', 'research', 'prevent',...","[-0.0381049859, 0.04797032, -0.029177214, 0.04...",11,Health & Family welfare Services
2,2,3,Ensure healthy lives and promote well-being fo...,"By 2030, reduce the maternal mortality ratio t...","['2030', 'reduce', 'maternal', 'mortality', 'r...","['child', 'road', 'implementation', 'research'...","[-0.0411676887, 0.0500096183, 0.0276913242, 0....",2,Area and Population
3,3,4,Ensure inclusive and equitable quality educati...,"By 2030, ensure that all girls and boys comple...","['2030', 'ensure', 'girl', 'boy', 'complete', ...","['child', 'people', 'substantially', 'scientif...","[-0.04538551, 0.00699968, 0.01054353, 0.049253...",2,Area and Population
4,4,5,Achieve gender equality and empower all women ...,End all forms of discrimination against all wo...,"['end', 'form', 'discrimination', 'woman', 'gi...","['child', 'decision', 'sphere', 'value', 'shar...","[-0.0391934204, 0.0135421753, 0.00412231445, 0...",2,Area and Population
5,5,6,"Ensure access to affordable, reliable, sustain...","By 2030, ensure universal access to affordable...","['2030', 'ensure', 'universal', 'access', 'aff...","['energy', 'affordable', 'modern', 'service', ...","[-0.05875651, -0.05223253, -0.00542535, -0.023...",2,Area and Population
6,6,6,Ensure availability and sustainable management...,"By 2030, achieve universal and equitable acces...","['2030', 'achieve', 'universal', 'equitable', ...","['material', 'people', 'drinking', 'substantia...","[-0.08247549, 0.06165522, 0.01714464, 0.016053...",2,Area and Population
7,7,7,"Ensure access to affordable, reliable, sustain...","By 2030, ensure universal access to affordable...","['2030', 'ensure', 'universal', 'access', 'aff...","['energy', 'accordance', 'research', 'double',...","[-0.11421156, 0.03368835, 0.02188492, 0.011013...",2,Area and Population
8,8,8,"Promote sustained, inclusive and sustainable e...",Sustain per capita economic growth in accordan...,"['sustain', 'capita', 'economic', 'growth', 'a...","['child', 'devise', 'worker', 'people', 'secur...","[-0.0273829869, 0.0283027528, -0.0150217934, 0...",12,Social Welfare
9,9,9,"Build resilient infrastructure, promote inclus...","Develop quality, reliable, sustainable and res...","['develop', 'quality', 'reliable', 'sustainabl...","['research', 'worker', 'double', 'chain', 'peo...","[-0.0718635718, 0.0255494714, -0.0183308919, 0...",4,"Agriculture, Horticulture and Sericulture"
10,10,10,Reduce inequality within the State,"By 2030, progressively achieve and sustain inc...","['2030', 'progressively', 'achieve', 'sustain'...","['disability', 'equality', 'equal', 'cent', 'e...","[-0.031618042, 0.0200415039, -0.0174108887, 0....",3,Rainfall
11,11,11,"Make cities and human settlements inclusive, s...","By 2030, ensure access for all to adequate, sa...","['2030', 'ensure', 'access', 'adequate', 'safe...","['child', 'positive', 'road', 'material', 'peo...","[-0.0478811, 0.04508594, 0.00164423, 0.0537863...",4,"Agriculture, Horticulture and Sericulture"
12,12,12,Ensure sustainable consumption and production\...,"By 2030, achieve the sustainable management an...","['2030', 'achieve', 'sustainable', 'management...","['harmony', 'cycle', 'chain', 'people', 'repor...","[-0.0815658362, 0.0597149393, -0.00235341943, ...",2,Area and Population
13,13,13,Take urgent action to combat climate change an...,Strengthen resilience and adaptive capacity to...,"['strengthen', 'resilience', 'adaptive', 'capa...","['strengthen', 'awareness', 'integrate', 'rais...","[-0.0102294922, 0.0748250326, 0.00590413411, 0...",7,Banks
14,14,14,"Protect, restore and promote sustainable use o...","By 2020, ensure the conservation, restoration ...","['2020', 'ensure', 'conservation', 'restoratio...","['inland', 'implementation', 'prevent', 'neutr...","[-0.0336039986, 0.0786299818, -0.00776079133, ...",7,Banks
15,15,15,Promote peaceful and inclusive societies for s...,Significantly reduce all forms of violence and...,"['significantly', 'reduce', 'form', 'violence'...","['strengthen', 'trafficking', 'recovery', 'chi...","[-0.07061774, 0.02596736, -0.00679421, 0.03344...",7,Banks
16,16,16,Strengthen the means of implementation and rev...,"Strengthen domestic resource mobilization, inc...","['strengthen', 'domestic', 'resource', 'mobili...","['strengthen', 'building', 'fully', 'include',...","[-0.0995303883, 0.0347529393, 0.00164196538, 0...",3,Rainfall
17,17,17,"Data, monitoring and accountability","By 2020, enhance capacity-building support to ...","['2020', 'enhance', 'capacity', 'build', 'supp...","['disability', '2020', 'building', 'ethnicity'...","[-0.0527105564, -0.0163410466, -0.0257464153, ...",2,Area and Population

In [61]:
new_df.to_csv('Chapter_2016-17.csv', sep=";")